// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: MainMenu

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainMenu
void ui_MainMenu_screen_init(void);
lv_obj_t *ui_MainMenu;
lv_obj_t *ui_MainMenuStatusBar;
lv_obj_t *ui_MainMenuNowPlayingPanel;
lv_obj_t *ui_MainMenuNowPlaying;
lv_obj_t *ui_MainMenuNowPlayingName;
lv_obj_t *ui_MainMenuLastViewedPanel;
lv_obj_t *ui_MainMenuLastViewed;
lv_obj_t *ui_MainMenuLastViewedName;
lv_obj_t *ui_MainMenuPanel;
lv_obj_t *ui_MenuPanelPatches;
lv_obj_t *ui_MenuImagePatches;
lv_obj_t *ui_MenuLabelPatches;
lv_obj_t *ui_MenuPanelSave;
lv_obj_t *ui_MenuImageSave;
lv_obj_t *ui_MenuLabelSave;
lv_obj_t *ui_MenuPanelSettings;
lv_obj_t *ui_MenuImageSettings;
lv_obj_t *ui_MenuLabelSettings;
lv_obj_t *ui_MainMenuLoadMeter;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_add[1] = {&ui_img_1x_add1_png};
const lv_img_dsc_t *ui_imgset_play[1] = {&ui_img_1x_play1_png};
const lv_img_dsc_t *ui_imgset_settings[1] = {&ui_img_1x_settings1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainMenu_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainMenu);
}
