#define THORVG_VERSION_STRING "1.0.0"

// #define THORVG_THREAD_SUPPORT 0
#define THORVG_SW_RASTER_SUPPORT 1
// #define THORVG_GL_RASTER_SUPPORT 0
// #define THORVG_WG_RASTER_SUPPORT 0

// #define THORVG_SVG_LOADER_SUPPORT 0
// #define THORVG_PNG_LOADER_SUPPORT 0
// #define THORVG_TTF_LOADER_SUPPORT 0

// #define THORVG_JPG_LOADER_SUPPORT 0
// #define THORVG_LOTTIE_LOADER_SUPPORT 0
// #define THORVG_WEBP_LOADER_SUPPORT 0
// #define THORVG_GIF_SAVER_SUPPORT 0

#define THORVG_NEON_VECTOR_SUPPORT 1
// #define THORVG_FILE_IO_SUPPORT 0
#define WIN32_LEAN_AND_MEAN 1
