#pragma once
#include "CoreModules/coreProcessor.h"
#include "CoreModules/module_info_base.hh"

struct SequantInfo : ModuleInfoBase {
    static constexpr std::string_view slug{"Sequant"};
    static constexpr std::string_view description{"2 Ch. 8 Step Sequencer w/ Quantizer"};
    static constexpr uint32_t width_hp = 17;
    static constexpr std::string_view svg_filename{"res/modules/Sequant-artwork.svg"};

    static constexpr int NumKnobs = 24;
    
    enum {
        KnobTempo = 0,
        KnobDelay = 1,
        KnobGate = 2,
        KnobSlew = 3,
        KnobStep_1N1 = 4,
        KnobStep_2N1 = 5,
        KnobStep_3N1 = 6,
        KnobStep_4N1 = 7,
        KnobStep_5N1 = 8,
        KnobStep_6N1 = 9,
        KnobStep_7N1 = 10,
        KnobStep_8N1 = 11,
        KnobStep_1N2 = 12,
        KnobStep_2N2 = 13,
        KnobStep_3N2 = 14,
        KnobStep_4N2 = 15,
        KnobStep_5N2 = 16,
        KnobStep_6N2 = 17,
        KnobStep_7N2 = 18,
        KnobStep_8N2 = 19,
        KnobScale = 20,
        KnobChance = 21,
        KnobRoot = 22,
        KnobRepeat = 23,
    };

    static constexpr std::array<KnobDef, NumKnobs> Knobs{{
        {
            .id = KnobTempo,
            .x_mm = px_to_mm<72>(64.34f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Tempo",
            .long_name = "Tempo",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobDelay,
            .x_mm = px_to_mm<72>(102.55f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Delay",
            .long_name = "Delay",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobGate,
            .x_mm = px_to_mm<72>(140.76f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Gate",
            .long_name = "Gate",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobSlew,
            .x_mm = px_to_mm<72>(178.96f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Slew",
            .long_name = "Slew",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_1N1,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 1-1",
            .long_name = "Step 1-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_2N1,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 2-1",
            .long_name = "Step 2-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_3N1,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 3-1",
            .long_name = "Step 3-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_4N1,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 4-1",
            .long_name = "Step 4-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_5N1,
            .x_mm = px_to_mm<72>(136.44f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 5-1",
            .long_name = "Step 5-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_6N1,
            .x_mm = px_to_mm<72>(164.79f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 6-1",
            .long_name = "Step 6-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_7N1,
            .x_mm = px_to_mm<72>(193.13f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 7-1",
            .long_name = "Step 7-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_8N1,
            .x_mm = px_to_mm<72>(221.48f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "Step 8-1",
            .long_name = "Step 8-1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_1N2,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 1-2",
            .long_name = "Step 1-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_2N2,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 2-2",
            .long_name = "Step 2-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_3N2,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 3-2",
            .long_name = "Step 3-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_4N2,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 4-2",
            .long_name = "Step 4-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_5N2,
            .x_mm = px_to_mm<72>(136.44f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 5-2",
            .long_name = "Step 5-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_6N2,
            .x_mm = px_to_mm<72>(164.79f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 6-2",
            .long_name = "Step 6-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_7N2,
            .x_mm = px_to_mm<72>(193.13f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 7-2",
            .long_name = "Step 7-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobStep_8N2,
            .x_mm = px_to_mm<72>(221.48f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "Step 8-2",
            .long_name = "Step 8-2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobScale,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(170.27f),
            .short_name = "Scale",
            .long_name = "Scale",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobChance,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(170.27f),
            .short_name = "Chance",
            .long_name = "Chance",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobRoot,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(211.46f),
            .short_name = "Root",
            .long_name = "Root",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobRepeat,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(211.46f),
            .short_name = "Repeat",
            .long_name = "Repeat",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
    }};

    static constexpr int NumInJacks = 5;
    
    enum {
        InputClock = 0,
        InputStart_Reset = 1,
        InputStop = 2,
        InputGate_In = 3,
        InputRepeat_Cv = 4,
    };

    static constexpr std::array<InJackDef, NumInJacks> InJacks{{
        {
            .id = InputClock,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Clock",
            .long_name = "Clock",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputStart_Reset,
            .x_mm = px_to_mm<72>(77.19f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Start/Reset",
            .long_name = "Start/Reset",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputStop,
            .x_mm = px_to_mm<72>(122.38f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Stop",
            .long_name = "Stop",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputGate_In,
            .x_mm = px_to_mm<72>(167.58f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Gate In",
            .long_name = "Gate In",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputRepeat_Cv,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Repeat CV",
            .long_name = "Repeat CV",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
    }};

    static constexpr int NumOutJacks = 5;
    
    enum {
        OutputClock_Out = 0,
        OutputStart_End = 1,
        OutputGate_Out = 2,
        OutputOut_1 = 3,
        OutputOut_2 = 4,
    };

    static constexpr std::array<OutJackDef, NumOutJacks> OutJacks{{
        {
            .id = OutputClock_Out,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Clock Out",
            .long_name = "Clock Out",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputStart_End,
            .x_mm = px_to_mm<72>(77.19f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Start/End",
            .long_name = "Start/End",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputGate_Out,
            .x_mm = px_to_mm<72>(122.25f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Gate Out",
            .long_name = "Gate Out",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputOut_1,
            .x_mm = px_to_mm<72>(167.58f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Out 1",
            .long_name = "Out 1",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputOut_2,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Out 2",
            .long_name = "Out 2",
            .signal_type = OutJackDef::Analog,
        },
    }};

    static constexpr int NumSwitches = 2;
    
    enum {
        SwitchStart_Stop = 0,
        SwitchSelect = 1,
    };

    static constexpr std::array<SwitchDef, NumSwitches> Switches{{
        {
            .id = SwitchStart_Stop,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Start/Stop",
            .long_name = "Start/Stop",
            .switch_type = SwitchDef::MomentaryButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchSelect,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Select",
            .long_name = "Select",
            .switch_type = SwitchDef::MomentaryButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
    }};

    static constexpr int NumDiscreteLeds = 8;
    
    enum {
        LedStep_1_Led = 0,
        LedStep_2_Led = 1,
        LedStep_3_Led = 2,
        LedStep_4_Led = 3,
        LedStep_5_Led = 4,
        LedStep_6_Led = 5,
        LedStep_7_Led = 6,
        LedStep_8_Led = 7,
    };

    static constexpr std::array<LedDef, NumDiscreteLeds> Leds{{
        {
            .id = LedStep_1_Led,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_2_Led,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_3_Led,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_4_Led,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_5_Led,
            .x_mm = px_to_mm<72>(136.44f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_6_Led,
            .x_mm = px_to_mm<72>(164.79f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_7_Led,
            .x_mm = px_to_mm<72>(193.13f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_8_Led,
            .x_mm = px_to_mm<72>(221.48f),
            .y_mm = px_to_mm<72>(118.26f),
            .led_color = LedDef::Red,
        },
    }};

};
