#pragma once

#include "drivers/stm32xx.h"

const RCC_OscInitTypeDef rcc_osc_conf = {
	.OscillatorType = RCC_OSCILLATORTYPE_HSE,
	.HSEState = RCC_HSE_ON,
	.PLL =
		{
			.PLLState = RCC_PLL_ON,
			.PLLSource = RCC_PLLSOURCE_HSE,
			.PLLM = 1,
			.PLLN = 60,
			.PLLP = 2,
			.PLLQ = 2,
			.PLLR = 2,
			.PLLRGE = RCC_PLL1VCIRANGE_3,
			.PLLVCOSEL = RCC_PLL1VCOWIDE,
			.PLLFRACN = 0,
		},
};

const RCC_ClkInitTypeDef rcc_clk_conf = {
	.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2 |
				 RCC_CLOCKTYPE_D3PCLK1 | RCC_CLOCKTYPE_D1PCLK1,
	.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK,
	.SYSCLKDivider = RCC_SYSCLK_DIV1,
	.AHBCLKDivider = RCC_HCLK_DIV2,
	.APB3CLKDivider = RCC_APB3_DIV2,
	.APB1CLKDivider = RCC_APB1_DIV2,
	.APB2CLKDivider = RCC_APB2_DIV2,
	.APB4CLKDivider = RCC_APB4_DIV2,
};

const RCC_PeriphCLKInitTypeDef rcc_periph_clk_conf = {
	.PeriphClockSelection = RCC_PERIPHCLK_UART4 | RCC_PERIPHCLK_USART1 | RCC_PERIPHCLK_SPI1 | RCC_PERIPHCLK_SPI2 |
							RCC_PERIPHCLK_I2C1 | RCC_PERIPHCLK_SPI6 | RCC_PERIPHCLK_SAI1 | RCC_PERIPHCLK_QSPI |
							RCC_PERIPHCLK_FMC,
	.PLL2 =
		{
			.PLL2M = 1,
			.PLL2N = 27,
			.PLL2P = 25,
			.PLL2Q = 3,
			.PLL2R = 2,
			.PLL2RGE = RCC_PLL2VCIRANGE_3,
			.PLL2VCOSEL = RCC_PLL2VCOMEDIUM,
			.PLL2FRACN = 0,
		},
	.PLL3 =
		{
			.PLL3M = 1,
			.PLL3N = 49,
			.PLL3P = 64,
			.PLL3Q = 2,
			.PLL3R = 2,
			.PLL3RGE = RCC_PLL3VCIRANGE_3,
			.PLL3VCOSEL = RCC_PLL3VCOWIDE,
			.PLL3FRACN = 1245,
		},
	.FmcClockSelection = RCC_FMCCLKSOURCE_PLL2,
	.QspiClockSelection = RCC_QSPICLKSOURCE_D1HCLK,
	.Sai1ClockSelection = RCC_SAI1CLKSOURCE_PLL3,
	.Spi123ClockSelection = RCC_SPI123CLKSOURCE_PLL,
	.Usart234578ClockSelection = RCC_USART234578CLKSOURCE_D2PCLK1,
	.Usart16ClockSelection = RCC_USART16CLKSOURCE_D2PCLK2,
	.I2c123ClockSelection = RCC_I2C123CLKSOURCE_D2PCLK1,
	.Spi6ClockSelection = RCC_SPI6CLKSOURCE_PLL2,
};
