// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: PatchView_Screen12

#include "../ui.h"

void ui_PatchView_screen_init(void) {
	ui_PatchView = lv_obj_create(NULL);
	lv_obj_clear_flag(ui_PatchView, LV_OBJ_FLAG_SCROLLABLE); /// Flags

	ui_MenuContainer = lv_obj_create(ui_PatchView);
	lv_obj_set_height(ui_MenuContainer, 50);
	lv_obj_set_width(ui_MenuContainer, lv_pct(100));
	lv_obj_set_align(ui_MenuContainer, LV_ALIGN_TOP_MID);
	lv_obj_set_flex_flow(ui_MenuContainer, LV_FLEX_FLOW_ROW);
	lv_obj_set_flex_align(
		ui_MenuContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
	lv_obj_clear_flag(ui_MenuContainer, LV_OBJ_FLAG_SCROLLABLE); /// Flags
	lv_obj_set_style_radius(ui_MenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_MenuContainer, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_MenuContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_img_opa(ui_MenuContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_img_recolor(ui_MenuContainer, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_img_recolor_opa(ui_MenuContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_MenuContainer, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_opa(ui_MenuContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_MenuContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_side(ui_MenuContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

	lv_obj_set_style_bg_color(ui_MenuContainer, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui_MenuContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

	ui_PlayButton = lv_imgbtn_create(ui_MenuContainer);
	lv_imgbtn_set_src(ui_PlayButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_play_light1_png, NULL);
	lv_imgbtn_set_src(ui_PlayButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_play_dark1_png, NULL);
	lv_obj_set_width(ui_PlayButton, 30);
	lv_obj_set_height(ui_PlayButton, 30);
	lv_obj_set_align(ui_PlayButton, LV_ALIGN_CENTER);
	lv_obj_set_style_radius(ui_PlayButton, 1, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_opa(ui_PlayButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_PlayButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_opa(ui_PlayButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_width(ui_PlayButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_pad(ui_PlayButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_PlayButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_opa(ui_PlayButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_width(ui_PlayButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_pad(ui_PlayButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

	ui_KnobButton = lv_imgbtn_create(ui_MenuContainer);
	lv_imgbtn_set_src(ui_KnobButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_knob_light1_png, NULL);
	lv_imgbtn_set_src(ui_KnobButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_knob_dark1_png, NULL);
	lv_obj_set_width(ui_KnobButton, 30);
	lv_obj_set_height(ui_KnobButton, 30);
	lv_obj_set_align(ui_KnobButton, LV_ALIGN_CENTER);
	lv_obj_set_style_radius(ui_KnobButton, 1, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_color(ui_KnobButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_opa(ui_KnobButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_KnobButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_opa(ui_KnobButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_width(ui_KnobButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_pad(ui_KnobButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_KnobButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_opa(ui_KnobButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_width(ui_KnobButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_pad(ui_KnobButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

	ui_AddButton = lv_imgbtn_create(ui_MenuContainer);
	lv_imgbtn_set_src(ui_AddButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_plus_light1_png, NULL);
	lv_imgbtn_set_src(ui_AddButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_plus_dark1_png, NULL);
	lv_obj_set_width(ui_AddButton, 30);
	lv_obj_set_height(ui_AddButton, 30);
	lv_obj_set_align(ui_AddButton, LV_ALIGN_CENTER);
	lv_obj_set_style_radius(ui_AddButton, 1, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_color(ui_AddButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_opa(ui_AddButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_AddButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_opa(ui_AddButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_width(ui_AddButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_pad(ui_AddButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_AddButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_opa(ui_AddButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_width(ui_AddButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_pad(ui_AddButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

	ui_InfoButton = lv_imgbtn_create(ui_MenuContainer);
	lv_imgbtn_set_src(ui_InfoButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_info_light3_png, NULL);
	lv_imgbtn_set_src(ui_InfoButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_info_dark3_png, NULL);
	lv_obj_set_width(ui_InfoButton, 30);
	lv_obj_set_height(ui_InfoButton, 30);
	lv_obj_set_align(ui_InfoButton, LV_ALIGN_CENTER);
	lv_obj_set_style_radius(ui_InfoButton, 1, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_InfoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_width(ui_InfoButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_pad(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_InfoButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_width(ui_InfoButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_pad(ui_InfoButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

	ui_SettingsButton = lv_imgbtn_create(ui_MenuContainer);
	lv_imgbtn_set_src(
		ui_SettingsButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_settings_light27_png, NULL);
	lv_imgbtn_set_src(ui_SettingsButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_settings_dark27_png, NULL);
	lv_obj_set_width(ui_SettingsButton, 30);
	lv_obj_set_height(ui_SettingsButton, 30);
	lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
	lv_obj_set_style_radius(ui_SettingsButton, 1, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_color(ui_SettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_bg_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_width(ui_SettingsButton, 2, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_pad(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_PRESSED);
	lv_obj_set_style_outline_color(ui_SettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_width(ui_SettingsButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
	lv_obj_set_style_outline_pad(ui_SettingsButton, 2, LV_PART_MAIN | LV_STATE_FOCUSED);

	ui_PatchName = lv_label_create(ui_PatchView);
	lv_obj_set_width(ui_PatchName, lv_pct(100));
	lv_obj_set_height(ui_PatchName, LV_SIZE_CONTENT); /// 1
	lv_obj_set_x(ui_PatchName, 0);
	lv_obj_set_y(ui_PatchName, 52);
	lv_obj_set_align(ui_PatchName, LV_ALIGN_TOP_MID);
	lv_label_set_long_mode(ui_PatchName, LV_LABEL_LONG_SCROLL_CIRCULAR);
	lv_label_set_text(ui_PatchName, "PATCH NAME HERE");
	lv_obj_set_style_text_color(ui_PatchName, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui_PatchName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui_PatchName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui_PatchName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_PatchName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_decor(ui_PatchName, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_PatchName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_PatchName, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_opa(ui_PatchName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_PatchName, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_border_side(ui_PatchName, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui_PatchName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui_PatchName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui_PatchName, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui_PatchName, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
}
