#pragma once
#include "CoreModules/coreProcessor.h"
#include "CoreModules/module_info_base.hh"

struct Gate32Info : ModuleInfoBase {
    static constexpr std::string_view slug{"Gate32"};
    static constexpr std::string_view description{"32 Step Gate Sequencer"};
    static constexpr uint32_t width_hp = 17;
    static constexpr std::string_view svg_filename{"res/modules/Gate32-artwork.svg"};

    static constexpr int NumKnobs = 4;
    
    enum {
        KnobTempo = 0,
        KnobDelay = 1,
        KnobGate = 2,
        KnobRepeat = 3,
    };

    static constexpr std::array<KnobDef, NumKnobs> Knobs{{
        {
            .id = KnobTempo,
            .x_mm = px_to_mm<72>(64.34f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Tempo",
            .long_name = "Tempo",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobDelay,
            .x_mm = px_to_mm<72>(102.55f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Delay",
            .long_name = "Delay",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobGate,
            .x_mm = px_to_mm<72>(140.76f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Gate",
            .long_name = "Gate",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobRepeat,
            .x_mm = px_to_mm<72>(178.96f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Repeat",
            .long_name = "Repeat",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
    }};

    static constexpr int NumInJacks = 5;
    
    enum {
        InputClock = 0,
        InputStart_Reset = 1,
        InputStop = 2,
        InputGate_Cv_Jack = 3,
        InputRepeat_Cv_Jack = 4,
    };

    static constexpr std::array<InJackDef, NumInJacks> InJacks{{
        {
            .id = InputClock,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Clock",
            .long_name = "Clock",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputStart_Reset,
            .x_mm = px_to_mm<72>(77.19f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Start/Reset",
            .long_name = "Start/Reset",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputStop,
            .x_mm = px_to_mm<72>(122.38f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Stop",
            .long_name = "Stop",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputGate_Cv_Jack,
            .x_mm = px_to_mm<72>(167.58f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Gate CV Jack",
            .long_name = "Gate CV Jack",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputRepeat_Cv_Jack,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Repeat CV Jack",
            .long_name = "Repeat CV Jack",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
    }};

    static constexpr int NumOutJacks = 5;
    
    enum {
        OutputClock_Out = 0,
        OutputStart_End = 1,
        OutputTrigger = 2,
        OutputInv = 3,
        OutputOut = 4,
    };

    static constexpr std::array<OutJackDef, NumOutJacks> OutJacks{{
        {
            .id = OutputClock_Out,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Clock Out",
            .long_name = "Clock Out",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputStart_End,
            .x_mm = px_to_mm<72>(77.19f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Start/End",
            .long_name = "Start/End",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputTrigger,
            .x_mm = px_to_mm<72>(122.25f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Trigger",
            .long_name = "Trigger",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputInv,
            .x_mm = px_to_mm<72>(167.58f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Inv",
            .long_name = "Inv",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputOut,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Out",
            .long_name = "Out",
            .signal_type = OutJackDef::Analog,
        },
    }};

    static constexpr int NumSwitches = 34;
    
    enum {
        SwitchStart_Stop = 0,
        SwitchSelect = 1,
        SwitchStep_1 = 2,
        SwitchStep_2 = 3,
        SwitchStep_3 = 4,
        SwitchStep_4 = 5,
        SwitchStep_5 = 6,
        SwitchStep_6 = 7,
        SwitchStep_7 = 8,
        SwitchStep_8 = 9,
        SwitchStep_9 = 10,
        SwitchStep_10 = 11,
        SwitchStep_11 = 12,
        SwitchStep_12 = 13,
        SwitchStep_13 = 14,
        SwitchStep_14 = 15,
        SwitchStep_15 = 16,
        SwitchStep_16 = 17,
        SwitchStep_17 = 18,
        SwitchStep_18 = 19,
        SwitchStep_19 = 20,
        SwitchStep_20 = 21,
        SwitchStep_21 = 22,
        SwitchStep_22 = 23,
        SwitchStep_23 = 24,
        SwitchStep_24 = 25,
        SwitchStep_25 = 26,
        SwitchStep_26 = 27,
        SwitchStep_27 = 28,
        SwitchStep_28 = 29,
        SwitchStep_29 = 30,
        SwitchStep_30 = 31,
        SwitchStep_31 = 32,
        SwitchStep_32 = 33,
    };

    static constexpr std::array<SwitchDef, NumSwitches> Switches{{
        {
            .id = SwitchStart_Stop,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Start/Stop",
            .long_name = "Start/Stop",
            .switch_type = SwitchDef::MomentaryButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchSelect,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Select",
            .long_name = "Select",
            .switch_type = SwitchDef::MomentaryButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_1,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 1",
            .long_name = "Step 1",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_2,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 2",
            .long_name = "Step 2",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_3,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 3",
            .long_name = "Step 3",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_4,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 4",
            .long_name = "Step 4",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_5,
            .x_mm = px_to_mm<72>(136.34f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 5",
            .long_name = "Step 5",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_6,
            .x_mm = px_to_mm<72>(164.69f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 6",
            .long_name = "Step 6",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_7,
            .x_mm = px_to_mm<72>(193.04f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 7",
            .long_name = "Step 7",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_8,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(92.5f),
            .short_name = "Step 8",
            .long_name = "Step 8",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_9,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 9",
            .long_name = "Step 9",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_10,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 10",
            .long_name = "Step 10",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_11,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 11",
            .long_name = "Step 11",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_12,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 12",
            .long_name = "Step 12",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_13,
            .x_mm = px_to_mm<72>(136.34f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 13",
            .long_name = "Step 13",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_14,
            .x_mm = px_to_mm<72>(164.69f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 14",
            .long_name = "Step 14",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_15,
            .x_mm = px_to_mm<72>(193.04f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 15",
            .long_name = "Step 15",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_16,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(133.27f),
            .short_name = "Step 16",
            .long_name = "Step 16",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_17,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 17",
            .long_name = "Step 17",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_18,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 18",
            .long_name = "Step 18",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_19,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 19",
            .long_name = "Step 19",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_20,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 20",
            .long_name = "Step 20",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_21,
            .x_mm = px_to_mm<72>(136.34f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 21",
            .long_name = "Step 21",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_22,
            .x_mm = px_to_mm<72>(164.69f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 22",
            .long_name = "Step 22",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_23,
            .x_mm = px_to_mm<72>(193.04f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 23",
            .long_name = "Step 23",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_24,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(174.05f),
            .short_name = "Step 24",
            .long_name = "Step 24",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_25,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 25",
            .long_name = "Step 25",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_26,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 26",
            .long_name = "Step 26",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_27,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 27",
            .long_name = "Step 27",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_28,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 28",
            .long_name = "Step 28",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_29,
            .x_mm = px_to_mm<72>(136.34f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 29",
            .long_name = "Step 29",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_30,
            .x_mm = px_to_mm<72>(164.69f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 30",
            .long_name = "Step 30",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_31,
            .x_mm = px_to_mm<72>(193.04f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 31",
            .long_name = "Step 31",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchStep_32,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(214.83f),
            .short_name = "Step 32",
            .long_name = "Step 32",
            .switch_type = SwitchDef::LatchingButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
    }};

    static constexpr int NumDiscreteLeds = 0;
    

    static constexpr std::array<LedDef, NumDiscreteLeds> Leds{{
    }};

};
