#pragma once
#include "CoreModules/coreProcessor.h"
#include "CoreModules/info/module_info_base.hh"

struct SequantInfo : ModuleInfoBase {
    static constexpr std::string_view slug{"Sequant"};
    static constexpr std::string_view description{"Step Sequencer and Quantizer"};
    static constexpr uint32_t width_hp = 17;
    static constexpr std::string_view svg_filename{"res/modules/Sequant-artwork.svg"};

    static constexpr int NumKnobs = 24;
    
    enum {
        KnobTempo = 0,
        KnobDelay = 1,
        KnobGate = 2,
        KnobSlew = 3,
        Knob_1_Ch1 = 4,
        Knob_2_Ch1 = 5,
        Knob_3_Ch1 = 6,
        Knob_4_Ch1 = 7,
        Knob_5_Ch1 = 8,
        Knob_6_Ch1 = 9,
        Knob_7_Ch1 = 10,
        Knob_8_Ch1 = 11,
        Knob_1_Ch2 = 12,
        Knob_2_Ch2 = 13,
        Knob_3_Ch2 = 14,
        Knob_4_Ch2 = 15,
        Knob_5_Ch2 = 16,
        Knob_6_Ch2 = 17,
        Knob_7_Ch2 = 18,
        Knob_8_Ch2 = 19,
        KnobScale = 20,
        KnobChance = 21,
        KnobRoot = 22,
        KnobRepeat = 23,
    };

    static constexpr std::array<KnobDef, NumKnobs> Knobs{{
        {
            .id = KnobTempo,
            .x_mm = px_to_mm<72>(64.34f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Tempo",
            .long_name = "Tempo",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobDelay,
            .x_mm = px_to_mm<72>(102.55f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Delay",
            .long_name = "Delay",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobGate,
            .x_mm = px_to_mm<72>(140.76f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Gate",
            .long_name = "Gate",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobSlew,
            .x_mm = px_to_mm<72>(178.96f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Slew",
            .long_name = "Slew",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_1_Ch1,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "1-Ch1",
            .long_name = "1-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_2_Ch1,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "2-Ch1",
            .long_name = "2-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_3_Ch1,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "3-Ch1",
            .long_name = "3-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_4_Ch1,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "4-Ch1",
            .long_name = "4-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_5_Ch1,
            .x_mm = px_to_mm<72>(136.44f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "5-Ch1",
            .long_name = "5-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_6_Ch1,
            .x_mm = px_to_mm<72>(164.79f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "6-Ch1",
            .long_name = "6-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_7_Ch1,
            .x_mm = px_to_mm<72>(193.13f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "7-Ch1",
            .long_name = "7-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_8_Ch1,
            .x_mm = px_to_mm<72>(221.48f),
            .y_mm = px_to_mm<72>(99.16f),
            .short_name = "8-Ch1",
            .long_name = "8-Ch1",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_1_Ch2,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "1-Ch2",
            .long_name = "1-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_2_Ch2,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "2-Ch2",
            .long_name = "2-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_3_Ch2,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "3-Ch2",
            .long_name = "3-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_4_Ch2,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "4-Ch2",
            .long_name = "4-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_5_Ch2,
            .x_mm = px_to_mm<72>(136.44f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "5-Ch2",
            .long_name = "5-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_6_Ch2,
            .x_mm = px_to_mm<72>(164.79f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "6-Ch2",
            .long_name = "6-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_7_Ch2,
            .x_mm = px_to_mm<72>(193.13f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "7-Ch2",
            .long_name = "7-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = Knob_8_Ch2,
            .x_mm = px_to_mm<72>(221.48f),
            .y_mm = px_to_mm<72>(137.36f),
            .short_name = "8-Ch2",
            .long_name = "8-Ch2",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobScale,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(170.27f),
            .short_name = "Scale",
            .long_name = "Scale",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobChance,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(170.27f),
            .short_name = "Chance",
            .long_name = "Chance",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobRoot,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(211.46f),
            .short_name = "Root",
            .long_name = "Root",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
        {
            .id = KnobRepeat,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(211.46f),
            .short_name = "Repeat",
            .long_name = "Repeat",
            .default_val = 0.0f,
            .knob_style = KnobDef::Small,
            .orientation = KnobDef::Round,
        },
    }};

    static constexpr int NumInJacks = 5;
    
    enum {
        InputClock = 0,
        InputReset = 1,
        InputStart_Stop = 2,
        InputGate = 3,
        InputRotate = 4,
    };

    static constexpr std::array<InJackDef, NumInJacks> InJacks{{
        {
            .id = InputClock,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Clock",
            .long_name = "Clock",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputReset,
            .x_mm = px_to_mm<72>(77.19f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Reset",
            .long_name = "Reset",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputStart_Stop,
            .x_mm = px_to_mm<72>(122.38f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Start/Stop",
            .long_name = "Start/Stop",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputGate,
            .x_mm = px_to_mm<72>(167.58f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Gate",
            .long_name = "Gate",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
        {
            .id = InputRotate,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(263.37f),
            .short_name = "Rotate",
            .long_name = "Rotate",
            .unpatched_val = 0.f,
            .signal_type = InJackDef::Analog,
        },
    }};

    static constexpr int NumOutJacks = 5;
    
    enum {
        OutputGate = 0,
        OutputTrigger = 1,
        OutputEnd = 2,
        OutputOut_1 = 3,
        OutputOut_2 = 4,
    };

    static constexpr std::array<OutJackDef, NumOutJacks> OutJacks{{
        {
            .id = OutputGate,
            .x_mm = px_to_mm<72>(31.99f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Gate",
            .long_name = "Gate",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputTrigger,
            .x_mm = px_to_mm<72>(77.19f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Trigger",
            .long_name = "Trigger",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputEnd,
            .x_mm = px_to_mm<72>(122.25f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "End",
            .long_name = "End",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputOut_1,
            .x_mm = px_to_mm<72>(167.58f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Out 1",
            .long_name = "Out 1",
            .signal_type = OutJackDef::Analog,
        },
        {
            .id = OutputOut_2,
            .x_mm = px_to_mm<72>(212.77f),
            .y_mm = px_to_mm<72>(310.96f),
            .short_name = "Out 2",
            .long_name = "Out 2",
            .signal_type = OutJackDef::Analog,
        },
    }};

    static constexpr int NumSwitches = 2;
    
    enum {
        SwitchStart = 0,
        SwitchSelect = 1,
    };

    static constexpr std::array<SwitchDef, NumSwitches> Switches{{
        {
            .id = SwitchStart,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Start",
            .long_name = "Start",
            .switch_type = SwitchDef::MomentaryButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
        {
            .id = SwitchSelect,
            .x_mm = px_to_mm<72>(221.38f),
            .y_mm = px_to_mm<72>(46.59f),
            .short_name = "Select",
            .long_name = "Select",
            .switch_type = SwitchDef::MomentaryButton,
            .orientation = SwitchDef::Round,
            .encoder_knob_style = SwitchDef::None,
        },
    }};

    static constexpr int NumDiscreteLeds = 8;
    
    enum {
        LedStep_1_Led = 0,
        LedStep_2_Led = 1,
        LedStep_3_Led = 2,
        LedStep_4_Led = 3,
        LedStep_5_Led = 4,
        LedStep_6_Led = 5,
        LedStep_7_Led = 6,
        LedStep_8_Led = 7,
    };

    static constexpr std::array<LedDef, NumDiscreteLeds> Leds{{
        {
            .id = LedStep_1_Led,
            .x_mm = px_to_mm<72>(221.48f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_2_Led,
            .x_mm = px_to_mm<72>(193.13f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_3_Led,
            .x_mm = px_to_mm<72>(164.79f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_4_Led,
            .x_mm = px_to_mm<72>(136.44f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_5_Led,
            .x_mm = px_to_mm<72>(108.0f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_6_Led,
            .x_mm = px_to_mm<72>(79.65f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_7_Led,
            .x_mm = px_to_mm<72>(51.3f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
        {
            .id = LedStep_8_Led,
            .x_mm = px_to_mm<72>(22.96f),
            .y_mm = px_to_mm<72>(79.31f),
            .led_color = LedDef::Red,
        },
    }};

};
