/*
 * Copyright 2021 NXP
 * SPDX-License-Identifier: MIT
 */

#ifndef GUI_GUIDER_H
#define GUI_GUIDER_H
#ifdef __cplusplus
extern "C" {
#endif

#include "guider_fonts.h"
#include "lvgl/lvgl.h"

typedef struct {
	lv_obj_t *Main_Example;
	lv_obj_t *Main_Example_btn_1;
	lv_obj_t *Main_Example_btn_1_label;
	lv_obj_t *Main_Example_btn_2;
	lv_obj_t *Main_Example_btn_2_label;
	lv_obj_t *Main_Example_btn_3;
	lv_obj_t *Main_Example_btn_3_label;
	lv_obj_t *Main_Example_btn_4;
	lv_obj_t *Main_Example_btn_4_label;
	lv_obj_t *Main_Example_btn_5;
	lv_obj_t *Main_Example_btn_5_label;
	lv_obj_t *Main_Example_btn_6;
	lv_obj_t *Main_Example_btn_6_label;
	lv_obj_t *Main_Example_arc_1;
	lv_obj_t *Main_Example_arc_2;
	lv_obj_t *Main_Example_arc_3;
	lv_obj_t *Main_Example_arc_4;
	lv_obj_t *Main_Example_arc_5;
	lv_obj_t *Main_Example_arc_6;
	lv_obj_t *Main_Example_label_1;
	lv_obj_t *Main_Example_label_2;
	lv_obj_t *Main_Example_label_3;
	lv_obj_t *symbol_sketches;
	lv_obj_t *symbol_sketches_sw_1;
	lv_obj_t *symbol_sketches_arc_1;
	lv_obj_t *symbol_sketches_slider_1;
	lv_obj_t *symbol_sketches_bar_1;
	lv_obj_t *symbol_sketches_bar_2;
	lv_obj_t *symbol_sketches_slider_2;
	lv_obj_t *symbol_sketches_slider_3;
	lv_obj_t *symbol_sketches_slider_4;
	lv_obj_t *symbol_sketches_slider_5;
	lv_obj_t *symbol_sketches_lmeter_2;
	lv_obj_t *symbol_sketches_slider_6;
	lv_obj_t *symbol_sketches_slider_7;
	lv_obj_t *symbol_sketches_ddlist_1;
	lv_obj_t *symbol_sketches_ddlist_2;
	lv_obj_t *AudioCV_Ins;
	lv_obj_t *AudioCV_Ins_cont_1;
	lv_obj_t *AudioCV_Ins_bar_1;
	lv_obj_t *AudioCV_Ins_bar_2;
	lv_obj_t *AudioCV_Ins_bar_3;
	lv_obj_t *AudioCV_Ins_bar_4;
	lv_obj_t *AudioCV_Ins_bar_5;
	lv_obj_t *AudioCV_Ins_bar_6;
	lv_obj_t *AudioCV_Ins_cont_2;
	lv_obj_t *AudioCV_Ins_label_3;
	lv_obj_t *AudioCV_Ins_label_4;
	lv_obj_t *AudioCV_Ins_label_6;
	lv_obj_t *AudioCV_Ins_label_7;
	lv_obj_t *AudioCV_Ins_label_8;
	lv_obj_t *AudioCV_Ins_label_9;
	lv_obj_t *AudioCV_Ins_label_10;
	lv_obj_t *AudioCV_Ins_label_11;
	lv_obj_t *AudioCV_Ins_bar_7;
	lv_obj_t *AudioCV_Ins_bar_8;
	lv_obj_t *AudioCV_Ins_bar_9;
	lv_obj_t *AudioCV_Ins_bar_10;
	lv_obj_t *AudioCV_Ins_bar_11;
	lv_obj_t *AudioCV_Ins_bar_12;
	lv_obj_t *AudioCV_Gates;
	lv_obj_t *AudioCV_Gates_bar_2;
	lv_obj_t *AudioCV_Gates_bar_3;
	lv_obj_t *AudioCV_Gates_bar_4;
	lv_obj_t *AudioCV_Gates_bar_5;
	lv_obj_t *AudioCV_Gates_bar_6;
	lv_obj_t *AudioCV_Gates_cont_2;
	lv_obj_t *AudioCV_Gates_label_3;
	lv_obj_t *AudioCV_Gates_label_4;
	lv_obj_t *AudioCV_Gates_label_6;
	lv_obj_t *AudioCV_Gates_label_7;
	lv_obj_t *AudioCV_Gates_label_8;
	lv_obj_t *AudioCV_Gates_label_9;
	lv_obj_t *AudioCV_Gates_label_10;
	lv_obj_t *AudioCV_Gates_label_11;
	lv_obj_t *AudioCV_Gates_bar_8;
	lv_obj_t *AudioCV_Gates_bar_13;
	lv_obj_t *AudioCV_Gates_bar_14;
	lv_obj_t *AudioCV_Gates_bar_15;
	lv_obj_t *AudioCV_Gates_bar_16;
	lv_obj_t *AudioCV_Gates_bar_17;
	lv_obj_t *AudioCV_Gates_bar_20;
	lv_obj_t *AudioCV_Gates_bar_22;
	lv_obj_t *AudioCV_Gates_bar_28;
	lv_obj_t *AudioCV_Gates_bar_29;
	lv_obj_t *AudioCV_Gates_bar_31;
	lv_obj_t *AudioCV_Gates_label_12;
	lv_obj_t *AudioCV_Gates_label_13;
	lv_obj_t *AudioCV_Gates_label_14;
	lv_obj_t *AudioCV_Gates_label_15;
	lv_obj_t *Knob_view3;
	lv_obj_t *Knob_view3_arc_1;
	lv_obj_t *Knob_view3_arc_2;
	lv_obj_t *Knob_view3_arc_3;
	lv_obj_t *Knob_view3_arc_4;
	lv_obj_t *Knob_view3_arc_5;
	lv_obj_t *Knob_view3_arc_6;
	lv_obj_t *Knob_view3_arc_7;
	lv_obj_t *Knob_view3_arc_8;
	lv_obj_t *Knob_view3_arc_9;
	lv_obj_t *Knob_view3_arc_10;
	lv_obj_t *Knob_view3_arc_11;
	lv_obj_t *Knob_view3_arc_12;
	lv_obj_t *Knob_view3_cont_1;
	lv_obj_t *Knob_view3_label_2;
	lv_obj_t *Knob_view3_label_3;
	lv_obj_t *Knob_view3_label_4;
	lv_obj_t *Knob_view3_label_5;
	lv_obj_t *Knob_view3_label_6;
	lv_obj_t *Knob_view3_label_7;
	lv_obj_t *Knob_view3_label_8;
	lv_obj_t *Knob_view3_label_9;
	lv_obj_t *Knob_view3_label_10;
	lv_obj_t *Knob_view3_label_11;
	lv_obj_t *Knob_view3_label_12;
	lv_obj_t *Knob_view3_label_13;
	lv_obj_t *module_test_small;
	lv_obj_t *module_test_small_SMR_panel;
	lv_obj_t *module_test_small_freq_nudge1;
	lv_obj_t *module_test_small_freq_nudge1_label;
	lv_obj_t *module_test_small_freq_cv1;
	lv_obj_t *module_test_small_freq_cv1_label;
	lv_obj_t *module_test_small_lock1;
	lv_obj_t *module_test_small_lock1_label;
	lv_obj_t *module_test_small_freq_switch1;
	lv_obj_t *module_test_small_freq_switch1_label;
	lv_obj_t *module_test_small_button_lock1;
	lv_obj_t *module_test_small_button_lock1_label;
	lv_obj_t *module_test_small_button_lock2;
	lv_obj_t *module_test_small_button_lock2_label;
	lv_obj_t *module_test_small_button_lock3;
	lv_obj_t *module_test_small_button_lock3_label;
	lv_obj_t *module_test_small_button_lock4;
	lv_obj_t *module_test_small_button_lock4_label;
	lv_obj_t *module_test_small_button_lock5;
	lv_obj_t *module_test_small_button_lock5_label;
	lv_obj_t *module_test_small_button_lock6;
	lv_obj_t *module_test_small_button_lock6_label;
	lv_obj_t *module_test_small_freq_nudge2;
	lv_obj_t *module_test_small_freq_nudge2_label;
	lv_obj_t *module_test_small_freq_cv2;
	lv_obj_t *module_test_small_freq_cv2_label;
	lv_obj_t *module_test_small_lock2;
	lv_obj_t *module_test_small_lock2_label;
	lv_obj_t *module_test_small_freq_switch2;
	lv_obj_t *module_test_small_freq_switch2_label;
	lv_obj_t *module_test_small_slider1;
	lv_obj_t *module_test_small_slider1_label;
	lv_obj_t *module_test_small_slider2;
	lv_obj_t *module_test_small_slider2_label;
	lv_obj_t *module_test_small_slider3;
	lv_obj_t *module_test_small_slider3_label;
	lv_obj_t *module_test_small_slider4;
	lv_obj_t *module_test_small_slider4_label;
	lv_obj_t *module_test_small_slider5;
	lv_obj_t *module_test_small_slider5_label;
	lv_obj_t *module_test_small_slider6;
	lv_obj_t *module_test_small_slider6_label;
	lv_obj_t *module_test_small_switch_cv_slew;
	lv_obj_t *module_test_small_switch_cv_slew_label;
	lv_obj_t *module_test_small_lvl_cv1;
	lv_obj_t *module_test_small_lvl_cv1_label;
	lv_obj_t *module_test_small_lvl_cv2;
	lv_obj_t *module_test_small_lvl_cv2_label;
	lv_obj_t *module_test_small_lvl_cv3;
	lv_obj_t *module_test_small_lvl_cv3_label;
	lv_obj_t *module_test_small_lvl_cv4;
	lv_obj_t *module_test_small_lvl_cv4_label;
	lv_obj_t *module_test_small_lvl_cv5;
	lv_obj_t *module_test_small_lvl_cv5_label;
	lv_obj_t *module_test_small_lvl_cv6;
	lv_obj_t *module_test_small_lvl_cv6_label;
	lv_obj_t *module_test_small_env_out1;
	lv_obj_t *module_test_small_env_out1_label;
	lv_obj_t *module_test_small_env_out2;
	lv_obj_t *module_test_small_env_out2_label;
	lv_obj_t *module_test_small_env_out3;
	lv_obj_t *module_test_small_env_out3_label;
	lv_obj_t *module_test_small_rotate_cv;
	lv_obj_t *module_test_small_rotate_cv_label;
	lv_obj_t *module_test_small_env_out4;
	lv_obj_t *module_test_small_env_out4_label;
	lv_obj_t *module_test_small_env_out5;
	lv_obj_t *module_test_small_env_out5_label;
	lv_obj_t *module_test_small_env_out6;
	lv_obj_t *module_test_small_env_out6_label;
	lv_obj_t *module_test_small_post_pre_switch;
	lv_obj_t *module_test_small_post_pre_switch_label;
	lv_obj_t *module_test_small_fast_slow_switch;
	lv_obj_t *module_test_small_fast_slow_switch_label;
	lv_obj_t *module_test_small_input_odds;
	lv_obj_t *module_test_small_input_odds_label;
	lv_obj_t *module_test_small_input_evens;
	lv_obj_t *module_test_small_input_evens_label;
	lv_obj_t *module_test_small_rotate_trig_cntr;
	lv_obj_t *module_test_small_rotate_trig_cntr_label;
	lv_obj_t *module_test_small_rotate_trig_clkw;
	lv_obj_t *module_test_small_rotate_trig_clkw_label;
	lv_obj_t *module_test_small_output_odds;
	lv_obj_t *module_test_small_output_odds_label;
	lv_obj_t *module_test_small_output_evens;
	lv_obj_t *module_test_small_output_evens_label;
	lv_obj_t *module_test_small_scale_cv;
	lv_obj_t *module_test_small_scale_cv_label;
	lv_obj_t *module_test_small_res_q_cv;
	lv_obj_t *module_test_small_res_q_cv_label;
	lv_obj_t *module_test_small_rotate_scale;
	lv_obj_t *module_test_small_rotate_scale_label;
	lv_obj_t *module_test_small_morph_cv;
	lv_obj_t *module_test_small_morph_cv_label;
	lv_obj_t *module_test_small_spread_cv;
	lv_obj_t *module_test_small_spread_cv_label;
	lv_obj_t *module_test_small_scale_r_switch;
	lv_obj_t *module_test_small_scale_r_switch_label;
	lv_obj_t *module_test_small_res_q;
	lv_obj_t *module_test_small_res_q_label;
	lv_obj_t *module_test_small_morph;
	lv_obj_t *module_test_small_morph_label;
	lv_obj_t *module_test_small_spread;
	lv_obj_t *module_test_small_spread_label;
	lv_obj_t *module_test_small_cont_1;
	lv_obj_t *module_test_small_roller_2;
	lv_obj_t *group_arc_sketches;
	lv_obj_t *group_arc_sketches_arc_1;
	lv_obj_t *group_arc_sketches_arc_2;
	lv_obj_t *group_arc_sketches_arc_3;
	lv_obj_t *group_arc_sketches_arc_4;
	lv_obj_t *group_arc_sketches_arc_5;
	lv_obj_t *group_arc_sketches_arc_6;
	lv_obj_t *group_arc_sketches_arc_7;
	lv_obj_t *group_arc_sketches_arc_8;
	lv_obj_t *group_arc_sketches_arc_9;
	lv_obj_t *group_arc_sketches_arc_10;
	lv_obj_t *group_arc_sketches_arc_11;
	lv_obj_t *group_arc_sketches_arc_12;
	lv_obj_t *group_arc_sketches2;
	lv_obj_t *group_arc_sketches2_arc_1;
	lv_obj_t *group_arc_sketches2_arc_2;
	lv_obj_t *group_arc_sketches2_arc_4;
	lv_obj_t *group_arc_sketches2_arc_3;
	lv_obj_t *group_arc_sketches2_arc_5;
	lv_obj_t *group_arc_sketches2_arc_6;
	lv_obj_t *group_arc_sketches3;
	lv_obj_t *group_arc_sketches3_arc_1;
	lv_obj_t *group_arc_sketches3_arc_2;
	lv_obj_t *group_arc_sketches3_arc_4;
	lv_obj_t *group_arc_sketches3_arc_3;
	lv_obj_t *group_arc_sketches3_arc_5;
	lv_obj_t *group_arc_sketches3_arc_6;
	lv_obj_t *group_arc_sketches3_arc_7;
	lv_obj_t *group_arc_sketches3_arc_8;
	lv_obj_t *group_arc_sketches3_arc_9;
	lv_obj_t *group_arc_sketches3_arc_10;
	lv_obj_t *group_arc_sketches3_arc_11;
	lv_obj_t *group_arc_sketches3_arc_12;
	lv_obj_t *group_arc_sketches4;
	lv_obj_t *group_arc_sketches4_arc_1;
	lv_obj_t *group_arc_sketches4_arc_2;
	lv_obj_t *group_arc_sketches4_arc_4;
	lv_obj_t *group_arc_sketches4_arc_3;
	lv_obj_t *group_arc_sketches4_arc_5;
	lv_obj_t *group_arc_sketches4_arc_6;
	lv_obj_t *group_arc_sketches4_arc_12;
	lv_obj_t *group_arc_sketches4_arc_11;
	lv_obj_t *group_arc_sketches4_arc_10;
	lv_obj_t *group_arc_sketches4_arc_9;
	lv_obj_t *group_arc_sketches4_arc_8;
} lv_ui;

void setup_ui(lv_ui *ui);
extern lv_ui guider_ui;
void setup_scr_Main_Example(lv_ui *ui);
void setup_scr_symbol_sketches(lv_ui *ui);
void setup_scr_AudioCV_Ins(lv_ui *ui);
void setup_scr_AudioCV_Gates(lv_ui *ui);
void setup_scr_Knob_view3(lv_ui *ui);
void setup_scr_module_test_small(lv_ui *ui);
void setup_scr_group_arc_sketches(lv_ui *ui);
void setup_scr_group_arc_sketches2(lv_ui *ui);
void setup_scr_group_arc_sketches3(lv_ui *ui);
void setup_scr_group_arc_sketches4(lv_ui *ui);
LV_IMG_DECLARE(back_but_orange_neg_57x100);

#ifdef __cplusplus
}
#endif
#endif
