
#ifndef GUIDER_FONTS_H
#define GUIDER_FONTS_H
#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/src/font/lv_font.h"

LV_FONT_DECLARE(lv_font_MuseoSansCondensed_700_16)
LV_FONT_DECLARE(lv_font_MuseoSansCondensed_700_13)
LV_FONT_DECLARE(lv_font_MuseoSansCondensed_700_12)
LV_FONT_DECLARE(lv_font_MuseoSansCondensed_700_10)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_700_17)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_700_16)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_500_16)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_500_12)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_700_14)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_700_13)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_700_12)
LV_FONT_DECLARE(lv_font_MuseoSansRounded_700_10)
LV_FONT_DECLARE(lv_font_simsun_12)
LV_FONT_DECLARE(myriad_16)

#ifdef __cplusplus
}
#endif
#endif
