Befaco_modules :=
Befaco_modules += EvenVCO
Befaco_modules += DualAtenuverter
Befaco_modules += SpringReverb
Befaco_modules += ABC
Befaco_modules += ADSR
Befaco_modules += ChoppingKinky
Befaco_modules += HexmixVCA
Befaco_modules += Kickall
Befaco_modules += Mixer
Befaco_modules += Morphader
Befaco_modules += MotionMTR
Befaco_modules += Percall
Befaco_modules += PonyVCO
Befaco_modules += Rampage
Befaco_modules += STMix
Befaco_modules += SamplingModulator
Befaco_modules += SlewLimiter
Befaco_modules += StereoStrip
# Befaco_modules += Muxlicer 
# Befaco_modules += NoisePlethora
