// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: META5

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PatchViewPage
void ui_PatchViewPage_screen_init(void);
lv_obj_t *ui_PatchViewPage;
lv_obj_t *ui_PatchName;
lv_obj_t *ui_ButtonsBG;
lv_obj_t *ui_ButtonsContainer;
lv_obj_t *ui_PlayButton;
void ui_event_KnobButton( lv_event_t * e);
lv_obj_t *ui_KnobButton;
lv_obj_t *ui_AddButton;
lv_obj_t *ui_InfoButton;
lv_obj_t *ui_SettingsButton;

// SCREEN: ui_Mapping_Menu
void ui_Mapping_Menu_screen_init(void);
lv_obj_t *ui_Mapping_Menu;
lv_obj_t *ui_MappingFlexZone;
lv_obj_t *ui_ModuleImage;
lv_obj_t *ui_MappingParameters;
lv_obj_t *ui_Module_Name;
lv_obj_t *ui_Element_Name;
lv_obj_t *ui_MappedWindow;
lv_obj_t *ui_Mappedto;
lv_obj_t *ui_EditMapButton;
void ui_event_ElementRoller( lv_event_t * e);
lv_obj_t *ui_ElementRoller;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_edit_map[2] = {&ui_img_1x_edit_map1_png, &ui_img_1x_edit_map2_png};
const lv_img_dsc_t *ui_imgset_asset_[6] = {&ui_img_button_circles_asset_34_png, &ui_img_button_circles_asset_35_png, &ui_img_button_circles_asset_36_png, &ui_img_button_circles_asset_46_png, &ui_img_button_circles_asset_47_png, &ui_img_button_circles_asset_48_png};
const lv_img_dsc_t *ui_imgset_dark_settings_focused_red[1] = {&ui_img_dark_icons_dark_settings_focused_red2_png};
const lv_img_dsc_t *ui_imgset_dark_settings_focused[1] = {&ui_img_dark_icons_dark_settings_focused3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_KnobButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_Mapping_Menu, LV_SCR_LOAD_ANIM_OVER_TOP, 1, 0);
}
}
void ui_event_ElementRoller( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_MappingParameters, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_ElementRoller, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_PatchViewPage_screen_init();
ui_Mapping_Menu_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_PatchViewPage);
}
