// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"


// COMPONENT MappedKnobSetItem

lv_obj_t *ui_MappedKnobSetItem_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_MappedKnobSetItem;
cui_MappedKnobSetItem = lv_btn_create(comp_parent);
lv_obj_set_height( cui_MappedKnobSetItem, 28);
lv_obj_set_width( cui_MappedKnobSetItem, lv_pct(100));
lv_obj_set_align( cui_MappedKnobSetItem, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_MappedKnobSetItem,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(cui_MappedKnobSetItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( cui_MappedKnobSetItem, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_MappedKnobSetItem, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(cui_MappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_MappedKnobSetItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_MappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_MappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_MappedKnobSetItem, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_MappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_MappedKnobSetItem, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_MappedKnobSetItem, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_MappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_MappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_MappedKnobSetItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_MappedKnobSetItem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_MappedKnobSetItem, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(cui_MappedKnobSetItem, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_MappedKnobSetItem, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_MappedKnobSetItem, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(cui_MappedKnobSetItem, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

lv_obj_t *cui_Circle;
cui_Circle = lv_btn_create(cui_MappedKnobSetItem);
lv_obj_set_width( cui_Circle, 22);
lv_obj_set_height( cui_Circle, 22);
lv_obj_set_align( cui_Circle, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( cui_Circle, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Circle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(cui_Circle, 22, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_Circle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_KnobLetter;
cui_KnobLetter = lv_label_create(cui_Circle);
lv_obj_set_width( cui_KnobLetter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_KnobLetter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_KnobLetter, LV_ALIGN_CENTER );
lv_label_set_text(cui_KnobLetter,"C");
lv_obj_set_style_text_color(cui_KnobLetter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_KnobLetter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_KnobLetter, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_KnobLetter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_KnobLetter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_KnobLetter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_KnobSetNameText;
cui_KnobSetNameText = lv_label_create(cui_MappedKnobSetItem);
lv_obj_set_height( cui_KnobSetNameText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_KnobSetNameText, 1);
lv_obj_set_align( cui_KnobSetNameText, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_KnobSetNameText,"Default");
lv_obj_clear_flag( cui_KnobSetNameText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(cui_KnobSetNameText, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_KnobSetNameText, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_KnobSetNameText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_KnobSetNameText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_KnobSetNameText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAPPEDKNOBSETITEM_NUM);
children[UI_COMP_MAPPEDKNOBSETITEM_MAPPEDKNOBSETITEM] = cui_MappedKnobSetItem;
children[UI_COMP_MAPPEDKNOBSETITEM_CIRCLE] = cui_Circle;
children[UI_COMP_MAPPEDKNOBSETITEM_CIRCLE_KNOBLETTER] = cui_KnobLetter;
children[UI_COMP_MAPPEDKNOBSETITEM_KNOBSETNAMETEXT] = cui_KnobSetNameText;
lv_obj_add_event_cb(cui_MappedKnobSetItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_MappedKnobSetItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_MappedKnobSetItem_create_hook(cui_MappedKnobSetItem);
return cui_MappedKnobSetItem; 
}

