// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

// COMPONENT UnmappedKnobSetItem

lv_obj_t *ui_UnmappedKnobSetItem_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_UnmappedKnobSetItem;
cui_UnmappedKnobSetItem = lv_obj_create(comp_parent);
lv_obj_set_width( cui_UnmappedKnobSetItem, lv_pct(100));
lv_obj_set_height( cui_UnmappedKnobSetItem, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_UnmappedKnobSetItem, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(cui_UnmappedKnobSetItem,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(cui_UnmappedKnobSetItem, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( cui_UnmappedKnobSetItem, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( cui_UnmappedKnobSetItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(cui_UnmappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_UnmappedKnobSetItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_UnmappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_UnmappedKnobSetItem, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_UnmappedKnobSetItem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_UnmappedKnobSetItem, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(cui_UnmappedKnobSetItem, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_UnmappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_UnmappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_UnmappedKnobSetItem, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_UnmappedKnobSetItem, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_UnmappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_UnmappedKnobSetItem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Panel4;
cui_Panel4 = lv_obj_create(cui_UnmappedKnobSetItem);
lv_obj_set_width( cui_Panel4, 22);
lv_obj_set_height( cui_Panel4, 18);
lv_obj_set_align( cui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_KnobSetNameText;
cui_KnobSetNameText = lv_label_create(cui_UnmappedKnobSetItem);
lv_obj_set_height( cui_KnobSetNameText, 15);
lv_obj_set_flex_grow( cui_KnobSetNameText, 1);
lv_obj_set_align( cui_KnobSetNameText, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(cui_KnobSetNameText,LV_LABEL_LONG_SCROLL);
lv_label_set_text(cui_KnobSetNameText,"Knob Set 23456");
lv_obj_clear_flag( cui_KnobSetNameText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(cui_KnobSetNameText, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_KnobSetNameText, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_KnobSetNameText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_KnobSetNameText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_KnobSetNameText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_AddMapButton;
cui_AddMapButton = lv_btn_create(cui_UnmappedKnobSetItem);
lv_obj_set_width( cui_AddMapButton, 21);
lv_obj_set_height( cui_AddMapButton, 21);
lv_obj_set_align( cui_AddMapButton, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_AddMapButton, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( cui_AddMapButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(cui_AddMapButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_AddMapButton, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_AddMapButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_AddMapButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_AddMapButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_AddMapButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(cui_AddMapButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_AddMapButton, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(cui_AddMapButton, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(cui_AddMapButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(cui_AddMapButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(cui_AddMapButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(cui_AddMapButton, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(cui_AddMapButton, 128, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

lv_obj_t *cui_PlusText2;
cui_PlusText2 = lv_label_create(cui_AddMapButton);
lv_obj_set_width( cui_PlusText2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_PlusText2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_PlusText2, LV_ALIGN_CENTER );
lv_label_set_text(cui_PlusText2,"+");
lv_obj_set_style_pad_left(cui_PlusText2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_PlusText2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_PlusText2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_PlusText2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_UNMAPPEDKNOBSETITEM_NUM);
children[UI_COMP_UNMAPPEDKNOBSETITEM_UNMAPPEDKNOBSETITEM] = cui_UnmappedKnobSetItem;
children[UI_COMP_UNMAPPEDKNOBSETITEM_PANEL4] = cui_Panel4;
children[UI_COMP_UNMAPPEDKNOBSETITEM_KNOBSETNAMETEXT] = cui_KnobSetNameText;
children[UI_COMP_UNMAPPEDKNOBSETITEM_ADDMAPBUTTON] = cui_AddMapButton;
children[UI_COMP_UNMAPPEDKNOBSETITEM_ADDMAPBUTTON_PLUSTEXT2] = cui_PlusText2;
lv_obj_add_event_cb(cui_UnmappedKnobSetItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_UnmappedKnobSetItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_UnmappedKnobSetItem_create_hook(cui_UnmappedKnobSetItem);
return cui_UnmappedKnobSetItem; 
}

