// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: META6

#ifndef _UI_COMP_UNMAPPEDSETITEM_H
#define _UI_COMP_UNMAPPEDSETITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT UnmappedSetItem
#define UI_COMP_UNMAPPEDSETITEM_UNMAPPEDSETITEM 0
#define UI_COMP_UNMAPPEDSETITEM_KNOBSETNAMETEXT 1
#define _UI_COMP_UNMAPPEDSETITEM_NUM 2
lv_obj_t *ui_UnmappedSetItem_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
