// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: META6

#ifndef _UI_COMP_CABLETOEDITBUTTON_H
#define _UI_COMP_CABLETOEDITBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT CableToEditButton
#define UI_COMP_CABLETOEDITBUTTON_CABLETOEDITBUTTON 0
#define UI_COMP_CABLETOEDITBUTTON_CABLETOLABEL 1
#define _UI_COMP_CABLETOEDITBUTTON_NUM 2
lv_obj_t *ui_CableToEditButton_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
