// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

// COMPONENT Button1

lv_obj_t *ui_Button1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Button1;
cui_Button1 = lv_btn_create(comp_parent);
lv_obj_set_width( cui_Button1, 70);
lv_obj_set_height( cui_Button1, 32);
lv_obj_set_align( cui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Button1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Button1, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(cui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(cui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(cui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(cui_Button1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(cui_Button1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Button1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_okaddlabel;
cui_okaddlabel = lv_label_create(cui_Button1);
lv_obj_set_width( cui_okaddlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_okaddlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_okaddlabel, 0 );
lv_obj_set_y( cui_okaddlabel, 1 );
lv_obj_set_align( cui_okaddlabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_okaddlabel,"OK");
lv_obj_set_style_text_color(cui_okaddlabel, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_okaddlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_okaddlabel, &ui_font_ArialNB16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON1_NUM);
children[UI_COMP_BUTTON1_BUTTON1] = cui_Button1;
children[UI_COMP_BUTTON1_OKADDLABEL] = cui_okaddlabel;
lv_obj_add_event_cb(cui_Button1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Button1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Button1_create_hook(cui_Button1);
return cui_Button1; 
}

