set(eightfoldModules
    SDOrcasHeartV2
)

set(EIGHTFOLD_DIR ${CMAKE_CURRENT_LIST_DIR}/../../eightfold)

list(TRANSFORM eightfoldModules PREPEND ${EIGHTFOLD_DIR}/res/ OUTPUT_VARIABLE EIGHTFOLD_FACEPLATE_SVGS)
list(TRANSFORM EIGHTFOLD_FACEPLATE_SVGS APPEND .svg)

list(TRANSFORM eightfoldModules PREPEND ${EIGHTFOLD_DIR}/src/ OUTPUT_VARIABLE EIGHTFOLD_SOURCE_PATHS)
list(TRANSFORM EIGHTFOLD_SOURCE_PATHS APPEND .cpp)
