// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: Main

#ifndef _UI_COMP_KNOBCONTAINERBIG_H
#define _UI_COMP_KNOBCONTAINERBIG_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

lv_obj_t *ui_KnobContainerBig_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
