#include "DejaVuSans12.c"
// #include "DejaVuSans12bw.c"
#include "DejaVuSerif16.c"
#include "DejaVuSerif32.c"
// #include "fixed_5x8.c"
#include "fixed_10x20.c"
#include "fixed_7x14.c"
// #include "DejaVuSans12bw_bwfont.c"
