#!/usr/bin/env python3
# Convert an image to an embedded RGB565 C header for the self-extract splash.
#
#   ./convert_logo.py boot_logo.png            -> splash_logo.h (128x128)
#   ./convert_logo.py boot_logo.png -o out.h -s 96
#   ./convert_logo.py --placeholder            -> a generated placeholder header
#
# The panel (ST7789, COLMOD 0x55) takes 16-bit RGB565, MSB byte first. The
# stub streams each pixel as (value>>8) then (value & 0xFF), so we emit the
# plain uint16 value = (R5<<11)|(G6<<5)|B5. Any alpha is composited over black
# (the splash background).

import argparse
import sys

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Pillow (PIL) is required: pip install Pillow")


def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def make_placeholder(w, h):
    # A simple, obviously-a-placeholder mark: white rounded-rectangle outline
    # with a filled centre dot on black. Replace by converting a real image.
    img = Image.new("RGB", (w, h), (0, 0, 0))
    d = ImageDraw.Draw(img)
    m = min(w, h) // 8
    d.rounded_rectangle([m, m, w - 1 - m, h - 1 - m],
                        radius=min(w, h) // 6, outline=(255, 255, 255), width=max(2, min(w, h) // 24))
    r = min(w, h) // 6
    d.ellipse([w // 2 - r, h // 2 - r, w // 2 + r, h // 2 + r], fill=(255, 255, 255))
    return img


def parse_size(s):
    # Accept "128" (square) or "92x41" (WxH).
    if "x" in s.lower():
        wx, hx = s.lower().split("x", 1)
        return int(wx), int(hx)
    n = int(s)
    return n, n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image", nargs="?", help="input image (PNG/BMP/...)")
    ap.add_argument("-o", "--out", default=None, help="output header (default: splash_logo.h next to this script)")
    ap.add_argument("-s", "--size", default="92x41", help="size in pixels: N (square) or WxH (default 92x41)")
    ap.add_argument("--placeholder", action="store_true", help="generate a placeholder instead of reading an image")
    args = ap.parse_args()

    w, h = parse_size(args.size)
    if args.placeholder or not args.image:
        img = make_placeholder(w, h)
        source = "placeholder"
    else:
        img = Image.open(args.image).convert("RGBA")
        # Composite over black, then resize to the target size.
        bg = Image.new("RGBA", img.size, (0, 0, 0, 255))
        img = Image.alpha_composite(bg, img).convert("RGB")
        if img.size != (w, h):
            img = img.resize((w, h), Image.LANCZOS)
        source = args.image

    px = img.load()
    vals = [to_rgb565(*px[x, y]) for y in range(h) for x in range(w)]

    import os
    out = args.out or os.path.join(os.path.dirname(os.path.abspath(__file__)), "splash_logo.h")

    lines = []
    lines.append("// Generated by convert_logo.py from %s -- do not edit by hand." % source)
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#define SPLASH_LOGO_W %d" % w)
    lines.append("#define SPLASH_LOGO_H %d" % h)
    lines.append("static const uint16_t splash_logo[%d] = {" % (w * h))
    row = "\t"
    for i, v in enumerate(vals):
        row += "0x%04X," % v
        if (i + 1) % 16 == 0:
            lines.append(row)
            row = "\t"
    if row.strip():
        lines.append(row)
    lines.append("};")

    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("Wrote %s (%dx%d, %d pixels) from %s" % (out, w, h, w * h, source))


if __name__ == "__main__":
    main()
