// For C:
#define DEBUG0_ON GPIOE->BSRR = GPIO_PIN_8
#define DEBUG0_OFF GPIOE->BSRR = (GPIO_PIN_8 << 16)

#define DEBUG1_ON GPIOE->BSRR = GPIO_PIN_7
#define DEBUG1_OFF GPIOE->BSRR = (GPIO_PIN_7 << 16)
