set(BEFACO_ONEIROI_DIR ${CMAKE_CURRENT_LIST_DIR}/../../BefacoOneiroi)

set(BefacoOneiroiModules
    Oneiroi
)

# svg paths
list(TRANSFORM BefacoOneiroiModules PREPEND ${BEFACO_ONEIROI_DIR}/res/panels/ OUTPUT_VARIABLE BEFACO_ONEIROI_FACEPLATE_SVGS)
list(TRANSFORM BEFACO_ONEIROI_FACEPLATE_SVGS APPEND .svg)

# cpp paths
list(TRANSFORM BefacoOneiroiModules PREPEND ${BEFACO_ONEIROI_DIR}/src/ OUTPUT_VARIABLE BEFACO_ONEIROI_SOURCE_PATHS)
list(TRANSFORM BEFACO_ONEIROI_SOURCE_PATHS APPEND .cpp)

file(GLOB DSP_SOURCES 
    ${BEFACO_ONEIROI_DIR}/libs/OwlProgram/LibSource/*.cpp
    ${BEFACO_ONEIROI_DIR}/libs/OwlProgram/LibSource/*.c
    ${BEFACO_ONEIROI_DIR}/libs/OwlProgram/Libraries/KissFFT/*.c
    libs/OwlProgram/LibSource/*.c
)

set(BEFACO_ONEIROI_SOURCE_PATHS ${BEFACO_ONEIROI_SOURCE_PATHS} ${DSP_SOURCES})