// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

void ui_CableMapPage_screen_init(void)
{
ui_CableMapPage = lv_obj_create(NULL);
lv_obj_clear_flag( ui_CableMapPage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_CableMapPage, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_CableMapPage, LV_DIR_VER);
lv_obj_set_flex_flow(ui_CableMapPage,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_CableMapPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_radius(ui_CableMapPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CableMapPage, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CableMapPage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_CableMapPage, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_CableMapPage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_CableMapPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_CableMapPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CableMapPage, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CableMapPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CableMapPage, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CableMapPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CableMapPage, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CableMapPage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CableMapPagePane = lv_obj_create(ui_CableMapPage);
lv_obj_set_width( ui_CableMapPagePane, lv_pct(100));
lv_obj_set_height( ui_CableMapPagePane, lv_pct(100));
lv_obj_set_x( ui_CableMapPagePane, -1 );
lv_obj_set_y( ui_CableMapPagePane, 0 );
lv_obj_set_align( ui_CableMapPagePane, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_CableMapPagePane,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_CableMapPagePane, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_CableMapPagePane, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CableMapPagePane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CableMapPagePane, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CableMapPagePane, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CableMapPagePane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CableMapPageTitle = lv_label_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableMapPageTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableMapPageTitle, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CableMapPageTitle,"Add/Edit Cable");
lv_obj_set_style_text_font(ui_CableMapPageTitle, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CableFromTitle = lv_label_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableFromTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableFromTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableFromTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_CableFromTitle,"From:");
lv_obj_add_flag( ui_CableFromTitle, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_CableFromTitle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_CableFromEditButton = lv_btn_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableFromEditButton, lv_pct(100));
lv_obj_set_height( ui_CableFromEditButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableFromEditButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CableFromEditButton, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_CableFromEditButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_CableFromEditButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CableFromEditButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CableFromEditButton, 128, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CableFromEditButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CableFromEditButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CableFromEditButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CableFromEditButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CableFromEditButton, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CableFromEditButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CableFromEditButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CableFromEditButton, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_CableFromEditButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_CableFromEditButton, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_bg_opa(ui_CableFromEditButton, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_CableFromLabel = lv_label_create(ui_CableFromEditButton);
lv_obj_set_width( ui_CableFromLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableFromLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableFromLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CableFromLabel,"Ensemble Oscillator #2, Output Audio B");
lv_obj_add_flag( ui_CableFromLabel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_CableFromLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_align(ui_CableFromLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CableFromLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CableFromLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CableFromLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CableFromLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CableFromLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CableFromLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CableToTitle = lv_label_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableToTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableToTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableToTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_CableToTitle,"To:");
lv_obj_add_flag( ui_CableToTitle, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_CableToTitle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_CableToPanel = lv_obj_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableToPanel, lv_pct(100));
lv_obj_set_height( ui_CableToPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_flow(ui_CableToPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_CableToPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_CableToPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_CableToPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CableToPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CableToPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CableToPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_CableToPanel, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_CableToPanel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_CableToPanel, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_CableToPanel, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_CableDeleteButton = lv_btn_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableDeleteButton, 30);
lv_obj_set_height( ui_CableDeleteButton, 30);
lv_obj_set_align( ui_CableDeleteButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CableDeleteButton, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CableDeleteButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_CableDeleteButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CableDeleteButton, lv_color_hex(0xE91C25), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CableDeleteButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CableDeleteButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CableDeleteButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CableDeleteButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CableDeleteButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_CableDeleteButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CableDeleteButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_CableDeleteButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_CableDeleteButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CableDeleteButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_CableDeleteButton, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CableDeleteButton, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_CableDeleteButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_CableDeleteButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_CableDeleteButton, lv_color_hex(0xE91C25), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_CableDeleteButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_CableDeleteButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_CableDeleteButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_CableDeleteIcon = lv_label_create(ui_CableDeleteButton);
lv_obj_set_width( ui_CableDeleteIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableDeleteIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableDeleteIcon, LV_ALIGN_CENTER );
lv_label_set_text(ui_CableDeleteIcon,"");
lv_obj_set_style_text_color(ui_CableDeleteIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CableDeleteIcon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_CableDeleteIcon, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_CableDeleteIcon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CableDeleteIcon, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CableDeleteIcon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CableDeleteIcon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CableDeleteIcon, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CableDeleteIcon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CableSave = lv_btn_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableSave, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableSave, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableSave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CableSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CableSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CableSaveLabel = lv_label_create(ui_CableSave);
lv_obj_set_width( ui_CableSaveLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableSaveLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableSaveLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CableSaveLabel,"Save");

ui_CableCancel = lv_btn_create(ui_CableMapPagePane);
lv_obj_set_width( ui_CableCancel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableCancel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableCancel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CableCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CableCancel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CableCancelLabel = lv_label_create(ui_CableCancel);
lv_obj_set_width( ui_CableCancelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CableCancelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CableCancelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CableCancelLabel,"Cancel");

}
