// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

void ui_DeleteMappingPopUp_screen_init(void)
{
ui_DeleteMappingPopUp = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DeleteMappingPopUp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_DeleteMappingPopUp, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_DeleteMappingPopUp, LV_DIR_VER);
lv_obj_set_flex_flow(ui_DeleteMappingPopUp,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_DeleteMappingPopUp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_radius(ui_DeleteMappingPopUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DeleteMappingPopUp, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DeleteMappingPopUp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_DeleteMappingPopUp, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_DeleteMappingPopUp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_DeleteMappingPopUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_DeleteMappingPopUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DeleteMappingPopUp, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DeleteMappingPopUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DeleteMappingPopUp, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DeleteMappingPopUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_DeleteMappingPopUp, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_DeleteMappingPopUp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelMapPopUpPanel = lv_obj_create(ui_DeleteMappingPopUp);
lv_obj_set_height( ui_DelMapPopUpPanel, 52);
lv_obj_set_width( ui_DelMapPopUpPanel, lv_pct(98));
lv_obj_set_align( ui_DelMapPopUpPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_DelMapPopUpPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_DelMapPopUpPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_DelMapPopUpPanel, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DelMapPopUpPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_DelMapPopUpPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DelMapPopUpPanel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DelMapPopUpPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DelMapPopUpPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_DelMapPopUpPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_DelMapPopUpPanel, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_DelMapPopUpPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_DelMapPopUpPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_DelMapPopUpPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DelMapPopUpPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DelMapPopUpPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DelMapPopUpPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DelMapPopUpPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_DelMapPopUpPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_DelMapPopUpPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelMapLabel = lv_label_create(ui_DelMapPopUpPanel);
lv_obj_set_width( ui_DelMapLabel, 180);
lv_obj_set_height( ui_DelMapLabel, 30);
lv_obj_set_align( ui_DelMapLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelMapLabel,"Are you sure you want to Delete this mapping?");
lv_obj_set_style_text_color(ui_DelMapLabel, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelMapLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_DelMapLabel, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelMapLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelMapLabel, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DelMapLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_DelMapLabel, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_DelMapLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DelMapLabel, -4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DelMapLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelMapButtonPanel = lv_obj_create(ui_DelMapPopUpPanel);
lv_obj_set_width( ui_DelMapButtonPanel, 110);
lv_obj_set_height( ui_DelMapButtonPanel, 50);
lv_obj_set_x( ui_DelMapButtonPanel, 0 );
lv_obj_set_y( ui_DelMapButtonPanel, 18 );
lv_obj_set_align( ui_DelMapButtonPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_DelMapButtonPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_DelMapButtonPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_DelMapButtonPanel, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_DelMapButtonPanel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_DelMapButtonPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_DelMapButtonPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DelMapButtonPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DelMapButtonPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DelMapButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DelMapButtonPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_DelMapButtonPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_DelMapButtonPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CancelButton = lv_btn_create(ui_DelMapButtonPanel);
lv_obj_set_width( ui_CancelButton, 62);
lv_obj_set_height( ui_CancelButton, 28);
lv_obj_set_align( ui_CancelButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CancelButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_CancelButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CancelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CancelButton, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CancelButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_CancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_CancelButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_CancelButton, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_CancelButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_CancelButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_CancelButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_CancelLabel = lv_label_create(ui_CancelButton);
lv_obj_set_width( ui_CancelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CancelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CancelLabel, -1 );
lv_obj_set_y( ui_CancelLabel, 0 );
lv_obj_set_align( ui_CancelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CancelLabel,"Cancel");
lv_obj_set_style_text_color(ui_CancelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CancelLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_CancelLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_CancelLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CancelLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TrashButton2 = lv_btn_create(ui_DelMapButtonPanel);
lv_obj_set_width( ui_TrashButton2, 30);
lv_obj_set_height( ui_TrashButton2, 30);
lv_obj_set_align( ui_TrashButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TrashButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TrashButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_TrashButton2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TrashButton2, lv_color_hex(0xE91C25), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TrashButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TrashButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TrashButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TrashButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TrashButton2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_TrashButton2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TrashButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_TrashButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TrashButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TrashButton2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_TrashButton2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TrashButton2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TrashButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_TrashButton2, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_TrashButton2, lv_color_hex(0xE91C25), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_TrashButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_TrashButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_TrashButton2, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_TrashLabel2 = lv_label_create(ui_TrashButton2);
lv_obj_set_width( ui_TrashLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TrashLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TrashLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_TrashLabel2,"");
lv_obj_set_style_text_color(ui_TrashLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TrashLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_TrashLabel2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TrashLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TrashLabel2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TrashLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TrashLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TrashLabel2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TrashLabel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}
