// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

void ui_MainMenu_screen_init(void)
{
ui_MainMenu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MainMenuNowPlayingPanel = lv_obj_create(ui_MainMenu);
lv_obj_set_height( ui_MainMenuNowPlayingPanel, 24);
lv_obj_set_width( ui_MainMenuNowPlayingPanel, lv_pct(100));
lv_obj_set_flex_flow(ui_MainMenuNowPlayingPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_MainMenuNowPlayingPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_add_flag( ui_MainMenuNowPlayingPanel, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_MainMenuNowPlayingPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_MainMenuNowPlayingPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_MainMenuNowPlayingPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainMenuNowPlayingPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainMenuNowPlayingPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainMenuNowPlayingPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainMenuNowPlayingPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainMenuNowPlayingPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainMenuNowPlayingPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainMenuNowPlayingPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainMenuNowPlayingPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainMenuNowPlayingPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MainMenuNowPlayingPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MainMenuNowPlayingPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMenuNowPlaying = lv_label_create(ui_MainMenuNowPlayingPanel);
lv_obj_set_height( ui_MainMenuNowPlaying, 20);
lv_obj_set_width( ui_MainMenuNowPlaying, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_MainMenuNowPlaying, 2 );
lv_obj_set_y( ui_MainMenuNowPlaying, 8 );
lv_obj_set_align( ui_MainMenuNowPlaying, LV_ALIGN_CENTER );
lv_label_set_text(ui_MainMenuNowPlaying,"Playing:");
lv_obj_clear_flag( ui_MainMenuNowPlaying, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_MainMenuNowPlaying, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_MainMenuNowPlaying, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainMenuNowPlaying, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainMenuNowPlaying, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainMenuNowPlaying, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMenuNowPlayingName = lv_label_create(ui_MainMenuNowPlayingPanel);
lv_obj_set_height( ui_MainMenuNowPlayingName, 20);
lv_obj_set_flex_grow( ui_MainMenuNowPlayingName, 1);
lv_obj_set_x( ui_MainMenuNowPlayingName, 2 );
lv_obj_set_y( ui_MainMenuNowPlayingName, 8 );
lv_obj_set_align( ui_MainMenuNowPlayingName, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_MainMenuNowPlayingName,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_MainMenuNowPlayingName,"MOtS Patch - EnOsc & Looping");
lv_obj_clear_flag( ui_MainMenuNowPlayingName, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_MainMenuNowPlayingName, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_MainMenuNowPlayingName, LV_DIR_LEFT);
lv_obj_set_style_text_color(ui_MainMenuNowPlayingName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainMenuNowPlayingName, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MainMenuNowPlayingName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_MainMenuNowPlayingName, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainMenuNowPlayingName, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MainMenuNowPlayingName, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainMenuNowPlayingName, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainMenuNowPlayingName, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainMenuNowPlayingName, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainMenuNowPlayingName, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMenuLoadMeter = lv_label_create(ui_MainMenuNowPlayingPanel);
lv_obj_set_width( ui_MainMenuLoadMeter, 38);
lv_obj_set_height( ui_MainMenuLoadMeter, 20);
lv_obj_set_x( ui_MainMenuLoadMeter, 0 );
lv_obj_set_y( ui_MainMenuLoadMeter, 2 );
lv_obj_set_align( ui_MainMenuLoadMeter, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_MainMenuLoadMeter,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_MainMenuLoadMeter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_label_set_text(ui_MainMenuLoadMeter,"1%");
lv_obj_clear_flag( ui_MainMenuLoadMeter, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_MainMenuLoadMeter, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_MainMenuLoadMeter, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MainMenuLoadMeter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_MainMenuLoadMeter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_MainMenuLoadMeter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MainMenuLoadMeter, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MainMenuLoadMeter, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MainMenuLoadMeter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainMenuLoadMeter, lv_color_hex(0x202328), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainMenuLoadMeter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainMenuLoadMeter, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainMenuLoadMeter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainMenuLoadMeter, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainMenuLoadMeter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMenuPanel = lv_obj_create(ui_MainMenu);
lv_obj_set_height( ui_MainMenuPanel, 140);
lv_obj_set_width( ui_MainMenuPanel, lv_pct(100));
lv_obj_set_align( ui_MainMenuPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MainMenuPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_MainMenuPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MainMenuPanel, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_MainMenuPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainMenuPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainMenuPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainMenuPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainMenuPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MainMenuPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MainMenuPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MainMenuPanel, lv_color_hex(0xFF8918), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainMenuPanel, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_MenuPanelPatches = lv_btn_create(ui_MainMenuPanel);
lv_obj_set_width( ui_MenuPanelPatches, 92);
lv_obj_set_height( ui_MenuPanelPatches, lv_pct(100));
lv_obj_set_align( ui_MenuPanelPatches, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MenuPanelPatches,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MenuPanelPatches, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_MenuPanelPatches, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuPanelPatches, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_MenuPanelPatches, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuPanelPatches, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MenuPanelPatches, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MenuPanelPatches, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MenuPanelPatches, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MenuPanelPatches, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MenuPanelPatches, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MenuPanelPatches, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuImagePatches = lv_img_create(ui_MenuPanelPatches);
lv_img_set_src(ui_MenuImagePatches, &ui_img_1x_play1_png);
lv_obj_set_width( ui_MenuImagePatches, 30);
lv_obj_set_height( ui_MenuImagePatches, 30);
lv_obj_set_align( ui_MenuImagePatches, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuImagePatches, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MenuImagePatches, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MenuLabelPatches = lv_label_create(ui_MenuPanelPatches);
lv_obj_set_width( ui_MenuLabelPatches, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_MenuLabelPatches, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MenuLabelPatches, LV_ALIGN_CENTER );
lv_label_set_text(ui_MenuLabelPatches,"Play\nPatch");
lv_obj_set_style_text_align(ui_MenuLabelPatches, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MenuLabelPatches, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuPanelSave = lv_btn_create(ui_MainMenuPanel);
lv_obj_set_width( ui_MenuPanelSave, 92);
lv_obj_set_height( ui_MenuPanelSave, lv_pct(100));
lv_obj_set_align( ui_MenuPanelSave, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MenuPanelSave,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MenuPanelSave, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_MenuPanelSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuPanelSave, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_MenuPanelSave, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuPanelSave, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MenuPanelSave, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MenuPanelSave, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MenuPanelSave, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MenuPanelSave, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MenuPanelSave, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MenuPanelSave, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuImageSave = lv_img_create(ui_MenuPanelSave);
lv_img_set_src(ui_MenuImageSave, &ui_img_1x_add1_png);
lv_obj_set_width( ui_MenuImageSave, 30);
lv_obj_set_height( ui_MenuImageSave, 30);
lv_obj_set_align( ui_MenuImageSave, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuImageSave, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MenuImageSave, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MenuLabelSave = lv_label_create(ui_MenuPanelSave);
lv_obj_set_width( ui_MenuLabelSave, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_MenuLabelSave, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MenuLabelSave, LV_ALIGN_CENTER );
lv_label_set_text(ui_MenuLabelSave,"New\nPatch");
lv_obj_set_style_text_align(ui_MenuLabelSave, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MenuLabelSave, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuPanelSettings = lv_btn_create(ui_MainMenuPanel);
lv_obj_set_width( ui_MenuPanelSettings, 92);
lv_obj_set_height( ui_MenuPanelSettings, lv_pct(100));
lv_obj_set_align( ui_MenuPanelSettings, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MenuPanelSettings,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MenuPanelSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_MenuPanelSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MenuPanelSettings, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_MenuPanelSettings, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MenuPanelSettings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MenuPanelSettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MenuPanelSettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MenuPanelSettings, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MenuPanelSettings, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MenuPanelSettings, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MenuPanelSettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MenuImageSettings = lv_img_create(ui_MenuPanelSettings);
lv_img_set_src(ui_MenuImageSettings, &ui_img_1x_settings1_png);
lv_obj_set_width( ui_MenuImageSettings, 30);
lv_obj_set_height( ui_MenuImageSettings, 30);
lv_obj_set_align( ui_MenuImageSettings, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MenuImageSettings, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MenuImageSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MenuLabelSettings = lv_label_create(ui_MenuPanelSettings);
lv_obj_set_width( ui_MenuLabelSettings, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_MenuLabelSettings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MenuLabelSettings, LV_ALIGN_CENTER );
lv_label_set_text(ui_MenuLabelSettings,"Settings");
lv_obj_set_style_text_font(ui_MenuLabelSettings, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_MenuPanelSystem = lv_btn_create(ui_MainMenuPanel);
// lv_obj_set_width( ui_MenuPanelSystem, 92);
// lv_obj_set_height( ui_MenuPanelSystem, lv_pct(100));
// lv_obj_set_align( ui_MenuPanelSystem, LV_ALIGN_CENTER );
// lv_obj_set_flex_flow(ui_MenuPanelSystem,LV_FLEX_FLOW_COLUMN);
// lv_obj_set_flex_align(ui_MenuPanelSystem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
// lv_obj_add_flag( ui_MenuPanelSystem, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
// lv_obj_clear_flag( ui_MenuPanelSystem, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
// lv_obj_set_style_bg_color(ui_MenuPanelSystem, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
// lv_obj_set_style_bg_opa(ui_MenuPanelSystem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_left(ui_MenuPanelSystem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_right(ui_MenuPanelSystem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_top(ui_MenuPanelSystem, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_bottom(ui_MenuPanelSystem, 13, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_row(ui_MenuPanelSystem, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_pad_column(ui_MenuPanelSystem, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_MenuImageSystem = lv_img_create(ui_MenuPanelSystem);
// lv_img_set_src(ui_MenuImageSystem, &ui_img_1x_info1_png);
// lv_obj_set_width( ui_MenuImageSystem, 30);
// lv_obj_set_height( ui_MenuImageSystem, 30);
// lv_obj_set_align( ui_MenuImageSystem, LV_ALIGN_CENTER );
// lv_obj_add_flag( ui_MenuImageSystem, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
// lv_obj_clear_flag( ui_MenuImageSystem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

// ui_MenuLabelSystem = lv_label_create(ui_MenuPanelSystem);
// lv_obj_set_width( ui_MenuLabelSystem, 100);
// lv_obj_set_height( ui_MenuLabelSystem, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_align( ui_MenuLabelSystem, LV_ALIGN_CENTER );
// lv_label_set_text(ui_MenuLabelSystem,"System");
// lv_obj_set_style_text_align(ui_MenuLabelSystem, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
// lv_obj_set_style_text_font(ui_MenuLabelSystem, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);

}
