// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

void ui_PatchViewPage0_screen_init(void)
{
ui_PatchViewPage0 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PatchViewPage0, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_PatchViewPage0, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_style_shadow_color(ui_PatchViewPage0, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PatchViewPage0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PatchViewPage0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonBarContainer = lv_obj_create(ui_PatchViewPage0);
lv_obj_set_height( ui_ButtonBarContainer, 50);
lv_obj_set_width( ui_ButtonBarContainer, lv_pct(100));
lv_obj_set_align( ui_ButtonBarContainer, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ButtonBarContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ButtonBarContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
lv_obj_clear_flag( ui_ButtonBarContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonBarContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonBarContainer, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBarContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_opa(ui_ButtonBarContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_ButtonBarContainer, lv_color_hex(0x666666), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_ButtonBarContainer, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ButtonBarContainer, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ButtonBarContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ButtonBarContainer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ButtonBarContainer, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ButtonBarContainer, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonBarContainer, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_PlayButton0 = lv_imgbtn_create(ui_ButtonBarContainer);
lv_imgbtn_set_src(ui_PlayButton0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_play_light1_png, NULL);
lv_imgbtn_set_src(ui_PlayButton0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_play_dark1_png, NULL);
lv_obj_set_width( ui_PlayButton0, 30);
lv_obj_set_height( ui_PlayButton0, 30);
lv_obj_set_align( ui_PlayButton0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PlayButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PlayButton0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PlayButton0, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_PlayButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PlayButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_PlayButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_PlayButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_PlayButton0, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_PlayButton0, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_PlayButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_PlayButton0, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_PlayButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_PlayButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_KnobButton0 = lv_imgbtn_create(ui_ButtonBarContainer);
lv_imgbtn_set_src(ui_KnobButton0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_knob_light1_png, NULL);
lv_imgbtn_set_src(ui_KnobButton0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_knob_dark1_png, NULL);
lv_obj_set_width( ui_KnobButton0, 30);
lv_obj_set_height( ui_KnobButton0, 30);
lv_obj_set_align( ui_KnobButton0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KnobButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_KnobButton0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_KnobButton0, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_KnobButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_KnobButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_KnobButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_KnobButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_KnobButton0, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_KnobButton0, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_KnobButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_KnobButton0, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_KnobButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_KnobButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_AddButton0 = lv_imgbtn_create(ui_ButtonBarContainer);
lv_imgbtn_set_src(ui_AddButton0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_plus_light1_png, NULL);
lv_imgbtn_set_src(ui_AddButton0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_plus_dark1_png, NULL);
lv_obj_set_width( ui_AddButton0, 30);
lv_obj_set_height( ui_AddButton0, 30);
lv_obj_set_align( ui_AddButton0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AddButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AddButton0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_AddButton0, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_AddButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_AddButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_AddButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_AddButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_AddButton0, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_AddButton0, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_AddButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_AddButton0, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_AddButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_AddButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_InfoButton0 = lv_imgbtn_create(ui_ButtonBarContainer);
lv_imgbtn_set_src(ui_InfoButton0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_info_light3_png, NULL);
lv_imgbtn_set_src(ui_InfoButton0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_info_dark3_png, NULL);
lv_obj_set_width( ui_InfoButton0, 30);
lv_obj_set_height( ui_InfoButton0, 30);
lv_obj_set_align( ui_InfoButton0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InfoButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InfoButton0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_InfoButton0, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_InfoButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_InfoButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_InfoButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_InfoButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_InfoButton0, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_InfoButton0, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_InfoButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_InfoButton0, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_InfoButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_InfoButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_SettingsButton0 = lv_imgbtn_create(ui_ButtonBarContainer);
lv_imgbtn_set_src(ui_SettingsButton0, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_symbols_raw_light_settings_light27_png, NULL);
lv_imgbtn_set_src(ui_SettingsButton0, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_symbols_raw_settings_dark27_png, NULL);
lv_obj_set_width( ui_SettingsButton0, 30);
lv_obj_set_height( ui_SettingsButton0, 30);
lv_obj_set_align( ui_SettingsButton0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsButton0, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_SettingsButton0, 1, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SettingsButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SettingsButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_SettingsButton0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_SettingsButton0, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_SettingsButton0, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_SettingsButton0, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_SettingsButton0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_SettingsButton0, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_SettingsButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_SettingsButton0, 2, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_PatchName0 = lv_label_create(ui_PatchViewPage0);
lv_obj_set_width( ui_PatchName0, lv_pct(100));
lv_obj_set_height( ui_PatchName0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PatchName0, 0 );
lv_obj_set_y( ui_PatchName0, 52 );
lv_obj_set_align( ui_PatchName0, LV_ALIGN_TOP_MID );
lv_label_set_long_mode(ui_PatchName0,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_PatchName0,"PATCH NAME HERE");
lv_obj_set_style_text_color(ui_PatchName0, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PatchName0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_PatchName0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_PatchName0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PatchName0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_PatchName0, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PatchName0, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PatchName0, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PatchName0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PatchName0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PatchName0, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PatchName0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PatchName0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PatchName0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PatchName0, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ModulesPanel0 = lv_obj_create(ui_PatchViewPage0);
lv_obj_set_width( ui_ModulesPanel0, 320);
lv_obj_set_height( ui_ModulesPanel0, 480);
lv_obj_set_x( ui_ModulesPanel0, 0 );
lv_obj_set_y( ui_ModulesPanel0, 83 );
lv_obj_set_flex_flow(ui_ModulesPanel0,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_ModulesPanel0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_ModulesPanel0, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_ModulesPanel0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ModulesPanel0, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_style_radius(ui_ModulesPanel0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ModulesPanel0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ModulesPanel0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ModulesPanel0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ModulesPanel0, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ModulesPanel0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ModulesPanel0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ModulesPanel0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ModulesPanel0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ModulesPanel0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_ModulesPanel0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_ModulesPanel0, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

}
