// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: META6

#include "../ui.h"

void ui_PatchViewPage2_screen_init(void)
{
ui_PatchViewPage2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PatchViewPage2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PatchViewPage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PatchViewPage2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PatchViewPage2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PatchViewPage2, lv_color_hex(0xEA1C25), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_PatchViewPage2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_PatchViewPage2, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_PatchViewPage2, 2, LV_PART_MAIN| LV_STATE_PRESSED);

ui_PatchName2 = lv_label_create(ui_PatchViewPage2);
lv_obj_set_width( ui_PatchName2, 320);
lv_obj_set_height( ui_PatchName2, 25);
lv_label_set_long_mode(ui_PatchName2,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_PatchName2,"PATCH NAME HERE PATCH NAME HERE");
lv_obj_set_style_text_color(ui_PatchName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PatchName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_PatchName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_PatchName2, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PatchName2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_PatchName2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PatchName2, &ui_font_Arial_16_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PatchName2, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PatchName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PatchName2, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PatchName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PatchName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PatchName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_PatchName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_PatchName2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_PatchName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PatchName2, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PatchName2, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PatchName2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PatchName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonsContainer2 = lv_obj_create(ui_PatchViewPage2);
lv_obj_set_width( ui_ButtonsContainer2, 320);
lv_obj_set_height( ui_ButtonsContainer2, 52);
lv_obj_set_x( ui_ButtonsContainer2, 0 );
lv_obj_set_y( ui_ButtonsContainer2, 27 );
lv_obj_set_flex_flow(ui_ButtonsContainer2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ButtonsContainer2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_ButtonsContainer2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonsContainer2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonsContainer2, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonsContainer2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ButtonsContainer2, lv_color_hex(0xEA1C25), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ButtonsContainer2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ButtonsContainer2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_ButtonsContainer2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ButtonsContainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_ButtonsContainer2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PlayButton2 = lv_imgbtn_create(ui_ButtonsContainer2);
lv_imgbtn_set_src(ui_PlayButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dark_icons_dark_play_png, NULL);
lv_imgbtn_set_src(ui_PlayButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_dark_icons_dark_play_press_png, NULL);
lv_obj_set_width( ui_PlayButton2, 34);
lv_obj_set_height( ui_PlayButton2, 34);
lv_obj_set_align( ui_PlayButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PlayButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PlayButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_PlayButton2, lv_color_hex(0x1E1E1E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_PlayButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_PlayButton2, 40, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_PlayButton2, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_PlayButton2, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_PlayButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_PlayButton2, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_PlayButton2, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_PlayButton2, lv_color_hex(0xFF9800), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_PlayButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_PlayButton2, 40, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_img_src( ui_PlayButton2, &ui_img_dark_icons_32px_circle_png, LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_color(ui_PlayButton2, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_PlayButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_PlayButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_PlayButton2, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_KnobButton2 = lv_imgbtn_create(ui_ButtonsContainer2);
lv_imgbtn_set_src(ui_KnobButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dark_icons_dark_knob_png, NULL);
lv_imgbtn_set_src(ui_KnobButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_dark_icons_dark_knob_press_png, NULL);
lv_obj_set_width( ui_KnobButton2, 34);
lv_obj_set_height( ui_KnobButton2, 34);
lv_obj_set_align( ui_KnobButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KnobButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_KnobButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_KnobButton2, lv_color_hex(0x1E1E1E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_KnobButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_KnobButton2, 40, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_KnobButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_KnobButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_KnobButton2, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_KnobButton2, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_KnobButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_KnobButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_KnobButton2, 40, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_img_src( ui_KnobButton2, &ui_img_dark_icons_32px_circle_png, LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_color(ui_KnobButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_KnobButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_KnobButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_KnobButton2, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_AddButton2 = lv_imgbtn_create(ui_ButtonsContainer2);
lv_imgbtn_set_src(ui_AddButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dark_icons_dark_add_png, NULL);
lv_imgbtn_set_src(ui_AddButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_dark_icons_dark_add_press_png, NULL);
lv_obj_set_width( ui_AddButton2, 34);
lv_obj_set_height( ui_AddButton2, 34);
lv_obj_set_align( ui_AddButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_AddButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AddButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_AddButton2, lv_color_hex(0x1E1E1E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_AddButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_AddButton2, 40, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_AddButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_AddButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_AddButton2, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_AddButton2, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_AddButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_AddButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_AddButton2, 40, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_img_src( ui_AddButton2, &ui_img_dark_icons_32px_circle_png, LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_color(ui_AddButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_AddButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_AddButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_AddButton2, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_InfoButton2 = lv_imgbtn_create(ui_ButtonsContainer2);
lv_imgbtn_set_src(ui_InfoButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dark_icons_dark_info_png, NULL);
lv_imgbtn_set_src(ui_InfoButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_dark_icons_dark_info_press_png, NULL);
lv_obj_set_width( ui_InfoButton2, 34);
lv_obj_set_height( ui_InfoButton2, 34);
lv_obj_set_align( ui_InfoButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InfoButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InfoButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_InfoButton2, lv_color_hex(0x1E1E1E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_InfoButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_InfoButton2, 40, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_color(ui_InfoButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_InfoButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_InfoButton2, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_InfoButton2, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_InfoButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_InfoButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_InfoButton2, 40, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_img_src( ui_InfoButton2, &ui_img_dark_icons_32px_circle_png, LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_color(ui_InfoButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_InfoButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_InfoButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_InfoButton2, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_SettingsButton2 = lv_imgbtn_create(ui_ButtonsContainer2);
lv_imgbtn_set_src(ui_SettingsButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_dark_icons_dark_settings_png, NULL);
lv_imgbtn_set_src(ui_SettingsButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_dark_icons_dark_settings_pressed_png, NULL);
lv_obj_set_width( ui_SettingsButton2, 34);
lv_obj_set_height( ui_SettingsButton2, 34);
lv_obj_set_align( ui_SettingsButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_img_recolor(ui_SettingsButton2, lv_color_hex(0x1E1E1E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_SettingsButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SettingsButton2, 40, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_SettingsButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_SettingsButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_img_src( ui_SettingsButton2, &ui_img_dark_icons_dark_settings_pressed_png, LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_color(ui_SettingsButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_outline_opa(ui_SettingsButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_width(ui_SettingsButton2, 2, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_outline_pad(ui_SettingsButton2, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_SettingsButton2, lv_color_hex(0x8B31FF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_SettingsButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_SettingsButton2, 40, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_img_src( ui_SettingsButton2, &ui_img_dark_icons_dark_settings_focused3_png, LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_color(ui_SettingsButton2, lv_color_hex(0x3342FF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_SettingsButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_SettingsButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_SettingsButton2, 3, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_ModulesPanel2 = lv_obj_create(ui_PatchViewPage2);
lv_obj_set_width( ui_ModulesPanel2, 320);
lv_obj_set_height( ui_ModulesPanel2, 480);
lv_obj_set_x( ui_ModulesPanel2, 0 );
lv_obj_set_y( ui_ModulesPanel2, 84 );
lv_obj_set_flex_flow(ui_ModulesPanel2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_ModulesPanel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_ModulesPanel2, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_ModulesPanel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_ModulesPanel2, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_style_radius(ui_ModulesPanel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ModulesPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ModulesPanel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ModulesPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ModulesPanel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ModulesPanel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}
