// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SystemMenu

#include "../ui.h"

void ui_SystemMenu_screen_init(void)
{
ui_SystemMenu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SystemMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SystemMenuTabView = lv_tabview_create(ui_SystemMenu, LV_DIR_LEFT, 90);
lv_obj_set_width( ui_SystemMenuTabView, lv_pct(100));
lv_obj_set_height( ui_SystemMenuTabView, lv_pct(100));
lv_obj_set_align( ui_SystemMenuTabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SystemMenuTabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemMenuTabView, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SystemMenuTabView, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SystemMenuTabView, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SystemMenuTabView, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SystemMenuTabView, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0x333333),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 8,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 8,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 4,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 4,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 8,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 8,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0x444444),  LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 0,  LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_SystemMenuTabView), LV_BORDER_SIDE_FULL,  LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0xFD8B18),  LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 128,  LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 2,  LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 3,  LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0xFD8B18),  LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 128,  LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 2,  LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 3,  LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_FOCUS_KEY);

lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_SystemMenuTabView), &ui_font_MuseoSansRounded70016,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 12,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0x777777),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 0,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 0,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0xFF8918),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 0,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 0,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 0,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0xFD8B18),  LV_PART_ITEMS | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_ITEMS| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_SystemMenuTabView), lv_color_hex(0xFD8B18),  LV_PART_ITEMS | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 255,  LV_PART_ITEMS| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 2,  LV_PART_ITEMS| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_SystemMenuTabView), 1,  LV_PART_ITEMS| LV_STATE_FOCUS_KEY);

ui_SystemMenuInfoTab = lv_tabview_add_tab(ui_SystemMenuTabView, "System");
lv_obj_set_flex_flow(ui_SystemMenuInfoTab,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SystemMenuInfoTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SystemMenuInfoTab, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_SystemMenuInfoTab, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenuInfoTab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SystemMenuInfoTab, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SystemMenuInfoTab, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SystemMenuInfoTab, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SystemMenuInfoTab, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SystemMenuInfoTab, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SystemMenuInfoTab, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SystemMenuInfoTab, lv_color_hex(0xFD8B18), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenuInfoTab, 128, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_SystemInfoCont = lv_obj_create(ui_SystemMenuInfoTab);
lv_obj_remove_style_all(ui_SystemInfoCont);
lv_obj_set_width( ui_SystemInfoCont, lv_pct(100));
lv_obj_set_height( ui_SystemInfoCont, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SystemInfoCont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SystemInfoCont,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SystemInfoCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_SystemInfoCont, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_SystemInfoCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_border_color(ui_SystemInfoCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SystemInfoCont, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SystemInfoCont, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SystemInfoCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SystemInfoCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SystemInfoCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SystemInfoCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SystemInfoCont, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SystemInfoCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SystemInfoCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuMetaModule = lv_label_create(ui_SystemInfoCont);
lv_obj_set_width( ui_SystemMenuMetaModule, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemMenuMetaModule, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuMetaModule, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuMetaModule,"MetaModule");
lv_obj_set_style_text_font(ui_SystemMenuMetaModule, &ui_font_MuseoSansRounded90018, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuPCBversion = lv_label_create(ui_SystemInfoCont);
lv_obj_set_width( ui_SystemMenuPCBversion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemMenuPCBversion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuPCBversion, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuPCBversion,"PCB version p11");
lv_obj_set_style_text_font(ui_SystemMenuPCBversion, &ui_font_MuseoSansRounded50014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuExpanders = lv_label_create(ui_SystemInfoCont);
lv_obj_set_width( ui_SystemMenuExpanders, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemMenuExpanders, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuExpanders, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuExpanders,"Expanders connected:");
lv_obj_set_style_text_font(ui_SystemMenuExpanders, &ui_font_MuseoSansRounded50014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuFWversion = lv_label_create(ui_SystemInfoCont);
lv_obj_set_width( ui_SystemMenuFWversion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemMenuFWversion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuFWversion, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuFWversion,"Firmware version 0.5.1");
lv_obj_set_style_text_font(ui_SystemMenuFWversion, &ui_font_MuseoSansRounded50014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemCalibrationCont = lv_obj_create(ui_SystemMenuInfoTab);
lv_obj_remove_style_all(ui_SystemCalibrationCont);
lv_obj_set_width( ui_SystemCalibrationCont, lv_pct(100));
lv_obj_set_height( ui_SystemCalibrationCont, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SystemCalibrationCont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SystemCalibrationCont,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SystemCalibrationCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SystemCalibrationCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_SystemCalibrationCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SystemCalibrationCont, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SystemCalibrationCont, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SystemCalibrationCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SystemCalibrationCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SystemCalibrationCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SystemCalibrationCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SystemCalibrationCont, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SystemCalibrationCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SystemCalibrationCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemCalibrationTitle = lv_label_create(ui_SystemCalibrationCont);
lv_obj_set_width( ui_SystemCalibrationTitle, lv_pct(100));
lv_obj_set_height( ui_SystemCalibrationTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemCalibrationTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemCalibrationTitle,"CV jack calibration:");
lv_obj_set_style_text_font(ui_SystemCalibrationTitle, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemCalibrationButton = lv_btn_create(ui_SystemCalibrationCont);
lv_obj_set_height( ui_SystemCalibrationButton, 28);
lv_obj_set_width( ui_SystemCalibrationButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_SystemCalibrationButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SystemCalibrationButton, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_SystemCalibrationButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_SystemCalibrationButton, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemCalibrationButton, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemCalibrationButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SystemCalibrationButton, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SystemCalibrationButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_SystemCalibrationButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_SystemCalibrationButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_SystemCalibrationButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_SystemCalibrationButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_SystemCalibrationButton, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_SystemCalibrationButtonLabel = lv_label_create(ui_SystemCalibrationButton);
lv_obj_set_width( ui_SystemCalibrationButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemCalibrationButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemCalibrationButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemCalibrationButtonLabel,"Re-calibrate jacks");
lv_obj_set_style_text_font(ui_SystemCalibrationButtonLabel, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemResetInternalPatchesCont = lv_obj_create(ui_SystemMenuInfoTab);
lv_obj_remove_style_all(ui_SystemResetInternalPatchesCont);
lv_obj_set_width( ui_SystemResetInternalPatchesCont, lv_pct(100));
lv_obj_set_height( ui_SystemResetInternalPatchesCont, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SystemResetInternalPatchesCont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SystemResetInternalPatchesCont,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SystemResetInternalPatchesCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SystemResetInternalPatchesCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_SystemResetInternalPatchesCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SystemResetInternalPatchesCont, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SystemResetInternalPatchesCont, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_SystemResetInternalPatchesCont, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SystemResetInternalPatchesCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SystemResetInternalPatchesCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SystemResetInternalPatchesCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SystemResetInternalPatchesCont, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SystemResetInternalPatchesCont, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SystemResetInternalPatchesCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ResetFactoryPatchesDescription = lv_label_create(ui_SystemResetInternalPatchesCont);
lv_obj_set_width( ui_ResetFactoryPatchesDescription, lv_pct(100));
lv_obj_set_height( ui_ResetFactoryPatchesDescription, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ResetFactoryPatchesDescription, LV_ALIGN_CENTER );
lv_label_set_text(ui_ResetFactoryPatchesDescription,"Factory Reset patches on Internal drive:");
lv_obj_set_style_text_font(ui_ResetFactoryPatchesDescription, &ui_font_MuseoSansRounded50014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ResetFactoryPatchesButton = lv_btn_create(ui_SystemResetInternalPatchesCont);
lv_obj_set_height( ui_ResetFactoryPatchesButton, 28);
lv_obj_set_width( ui_ResetFactoryPatchesButton, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_ResetFactoryPatchesButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ResetFactoryPatchesButton, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_clear_flag( ui_ResetFactoryPatchesButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ResetFactoryPatchesButton, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ResetFactoryPatchesButton, lv_color_hex(0xE91C25), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ResetFactoryPatchesButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ResetFactoryPatchesButton, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_ResetFactoryPatchesButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_ResetFactoryPatchesButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_ResetFactoryPatchesButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_ResetFactoryPatchesButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_ResetFactoryPatchesButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_ResetFactoryPatchesButton, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_ResetFactoryPatchesLabel = lv_label_create(ui_ResetFactoryPatchesButton);
lv_obj_set_width( ui_ResetFactoryPatchesLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ResetFactoryPatchesLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ResetFactoryPatchesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ResetFactoryPatchesLabel,"Reset Factory Patches");
lv_obj_set_style_text_font(ui_ResetFactoryPatchesLabel, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuTest = lv_tabview_add_tab(ui_SystemMenuTabView, "Plugins");
lv_obj_set_flex_flow(ui_SystemMenuTest,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SystemMenuTest, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_SystemMenuTest, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenuTest, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SystemMenuTest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SystemMenuTest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SystemMenuTest, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SystemMenuTest, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginsLeftColumn = lv_obj_create(ui_SystemMenuTest);
lv_obj_remove_style_all(ui_PluginsLeftColumn);
lv_obj_set_width( ui_PluginsLeftColumn, lv_pct(48));
lv_obj_set_height( ui_PluginsLeftColumn, lv_pct(100));
lv_obj_set_x( ui_PluginsLeftColumn, 0 );
lv_obj_set_y( ui_PluginsLeftColumn, 2 );
lv_obj_set_align( ui_PluginsLeftColumn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PluginsLeftColumn,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PluginsLeftColumn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PluginsLeftColumn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_PluginsLeftColumn, LV_DIR_VER);
lv_obj_set_style_pad_left(ui_PluginsLeftColumn, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsLeftColumn, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsLeftColumn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsLeftColumn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginsFoundTitle = lv_label_create(ui_PluginsLeftColumn);
lv_obj_set_width( ui_PluginsFoundTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PluginsFoundTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginsFoundTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_PluginsFoundTitle,"Plugins Found:");
lv_obj_set_style_text_color(ui_PluginsFoundTitle, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PluginsFoundTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PluginsFoundTitle, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginsFoundTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsFoundTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsFoundTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsFoundTitle, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginScanButton = lv_btn_create(ui_PluginsLeftColumn);
lv_obj_set_width( ui_PluginScanButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PluginScanButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginScanButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PluginScanButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PluginScanButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PluginScanButton, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PluginScanButton, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PluginScanButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_PluginScanButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PluginScanButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PluginScanButton, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PluginScanButton, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_PluginScanButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_PluginScanButton, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_PluginScanButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_PluginScanButton, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_PluginScanButton, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_PluginScanButtonLabel = lv_label_create(ui_PluginScanButton);
lv_obj_set_width( ui_PluginScanButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PluginScanButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginScanButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PluginScanButtonLabel,"Scan disks");

ui_PluginsFoundCont = lv_obj_create(ui_PluginsLeftColumn);
lv_obj_remove_style_all(ui_PluginsFoundCont);
lv_obj_set_height( ui_PluginsFoundCont, 152);
lv_obj_set_width( ui_PluginsFoundCont, lv_pct(100));
lv_obj_set_align( ui_PluginsFoundCont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PluginsFoundCont,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PluginsFoundCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_PluginsFoundCont, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_EVENT_BUBBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PluginsFoundCont, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_PluginsFoundCont, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_PluginsFoundCont, LV_DIR_VER);
lv_obj_set_style_pad_left(ui_PluginsFoundCont, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsFoundCont, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsFoundCont, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsFoundCont, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PluginsFoundCont, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PluginsFoundCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_PluginsFoundCont, 3, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PluginsFoundCont, lv_color_hex(0xFD8B18), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PluginsFoundCont, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_PluginFoundButton1 = lv_btn_create(ui_PluginsFoundCont);
lv_obj_set_height( ui_PluginFoundButton1, 23);
lv_obj_set_width( ui_PluginFoundButton1, lv_pct(100));
lv_obj_set_align( ui_PluginFoundButton1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_PluginFoundButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PluginFoundButton1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_PluginFoundButton1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_PluginFoundButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PluginFoundButton1, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PluginFoundButton1, 64, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginFoundButton1, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginFoundButton1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginFoundButton1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginFoundButton1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PluginFoundButton1, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_PluginFoundButton1, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_PluginFoundButton1, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_PluginFoundButton1, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_PluginFoundButton1, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_PluginFoundButton1, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(ui_PluginFoundButton1, 2, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(ui_PluginFoundButton1, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_PluginFoundButtonLabel1 = lv_label_create(ui_PluginFoundButton1);
lv_obj_set_width( ui_PluginFoundButtonLabel1, lv_pct(100));
lv_obj_set_height( ui_PluginFoundButtonLabel1, lv_pct(100));
lv_obj_set_align( ui_PluginFoundButtonLabel1, LV_ALIGN_LEFT_MID );
lv_label_set_long_mode(ui_PluginFoundButtonLabel1,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_PluginFoundButtonLabel1,"BogaudioModules");
lv_obj_set_style_text_font(ui_PluginFoundButtonLabel1, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginsRightColumn = lv_obj_create(ui_SystemMenuTest);
lv_obj_remove_style_all(ui_PluginsRightColumn);
lv_obj_set_width( ui_PluginsRightColumn, lv_pct(48));
lv_obj_set_height( ui_PluginsRightColumn, lv_pct(100));
lv_obj_set_align( ui_PluginsRightColumn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PluginsRightColumn,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PluginsRightColumn, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PluginsRightColumn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_PluginsRightColumn, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_PluginsRightColumn, LV_DIR_VER);

lv_obj_set_style_radius(ui_PluginsRightColumn, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PluginsRightColumn, lv_color_hex(0xFD8B18), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PluginsRightColumn, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PluginsRightColumn, lv_color_hex(0xFD8B18), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PluginsRightColumn, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PluginsRightColumn, 2, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PluginsRightColumn, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginsRightColumn, -8, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsRightColumn, -8, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsRightColumn, -8, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsRightColumn, -8, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_PluginsLoadedTitle = lv_label_create(ui_PluginsRightColumn);
lv_obj_set_width( ui_PluginsLoadedTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PluginsLoadedTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginsLoadedTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_PluginsLoadedTitle,"Plugins Loaded:");
lv_obj_set_style_text_color(ui_PluginsLoadedTitle, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PluginsLoadedTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PluginsLoadedTitle, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginsLoadedTitle, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsLoadedTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsLoadedTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsLoadedTitle, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginsLoadedCont = lv_obj_create(ui_PluginsRightColumn);
lv_obj_remove_style_all(ui_PluginsLoadedCont);
lv_obj_set_height( ui_PluginsLoadedCont, 161);
lv_obj_set_width( ui_PluginsLoadedCont, lv_pct(100));
lv_obj_set_align( ui_PluginsLoadedCont, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PluginsLoadedCont,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PluginsLoadedCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PluginsLoadedCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_PluginsLoadedCont, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_PluginsLoadedCont, LV_DIR_VER);
lv_obj_set_style_pad_left(ui_PluginsLoadedCont, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsLoadedCont, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsLoadedCont, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsLoadedCont, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PluginsLoadedCont, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PluginsLoadedCont, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginFoundButton2 = lv_btn_create(ui_PluginsLoadedCont);
lv_obj_set_width( ui_PluginFoundButton2, lv_pct(100));
lv_obj_set_height( ui_PluginFoundButton2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginFoundButton2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PluginFoundButton2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PluginFoundButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PluginFoundButton2, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PluginFoundButton2, 64, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginFoundButton2, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginFoundButton2, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginFoundButton2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginFoundButton2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PluginFoundButton2, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PluginFoundButton2, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_PluginFoundButton2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_PluginFoundButton2, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_PluginFoundButton2, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_PluginFoundButton2, lv_color_hex(0xFDB818), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_PluginFoundButton2, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(ui_PluginFoundButton2, 2, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(ui_PluginFoundButton2, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_PluginFoundButtonLabel2 = lv_label_create(ui_PluginFoundButton2);
lv_obj_set_width( ui_PluginFoundButtonLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PluginFoundButtonLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginFoundButtonLabel2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_PluginFoundButtonLabel2,"Valley");
lv_obj_set_style_text_font(ui_PluginFoundButtonLabel2, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginsBuiltinTitle = lv_label_create(ui_PluginsLoadedCont);
lv_obj_set_width( ui_PluginsBuiltinTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PluginsBuiltinTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginsBuiltinTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_PluginsBuiltinTitle,"Built-in:");
lv_obj_add_flag( ui_PluginsBuiltinTitle, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_PluginsBuiltinTitle, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PluginsBuiltinTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PluginsBuiltinTitle, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginsBuiltinTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsBuiltinTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsBuiltinTitle, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsBuiltinTitle, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PluginsBuiltinListText = lv_label_create(ui_PluginsLoadedCont);
lv_obj_set_width( ui_PluginsBuiltinListText, lv_pct(97));
lv_obj_set_height( ui_PluginsBuiltinListText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PluginsBuiltinListText, LV_ALIGN_CENTER );
lv_label_set_text(ui_PluginsBuiltinListText,"4ms\nBefaco\nHetrickCV\nNonlinearCircuits\nEightfold\nMorphable Instr.");
lv_obj_add_flag( ui_PluginsBuiltinListText, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PluginsBuiltinListText, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_PluginsBuiltinListText, LV_DIR_VER);
lv_obj_set_style_text_letter_space(ui_PluginsBuiltinListText, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_PluginsBuiltinListText, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PluginsBuiltinListText, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PluginsBuiltinListText, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PluginsBuiltinListText, 64, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PluginsBuiltinListText, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PluginsBuiltinListText, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PluginsBuiltinListText, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PluginsBuiltinListText, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PluginsBuiltinListText, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_PluginsBuiltinListText, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_PluginsBuiltinListText, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_PluginsBuiltinListText, 1, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_PluginsBuiltinListText, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_PluginsBuiltinListText, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_width(ui_PluginsBuiltinListText, 2, LV_PART_MAIN| LV_STATE_FOCUS_KEY);
lv_obj_set_style_outline_pad(ui_PluginsBuiltinListText, 1, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_PluginTabSpinner = lv_spinner_create(ui_SystemMenuTest,1000,90);
lv_obj_set_width( ui_PluginTabSpinner, 50);
lv_obj_set_height( ui_PluginTabSpinner, 50);
lv_obj_set_align( ui_PluginTabSpinner, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PluginTabSpinner, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING );   /// Flags
lv_obj_clear_flag( ui_PluginTabSpinner, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_arc_color(ui_PluginTabSpinner, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PluginTabSpinner, 64, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PluginTabSpinner, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_PluginTabSpinner, lv_color_hex(0xFF8918), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PluginTabSpinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PluginTabSpinner, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_SystemMenuPrefs = lv_tabview_add_tab(ui_SystemMenuTabView, "Prefs");
lv_obj_set_flex_flow(ui_SystemMenuPrefs,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SystemMenuPrefs, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_SystemMenuPrefs, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenuPrefs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuUpdateTab = lv_tabview_add_tab(ui_SystemMenuTabView, "Update");
lv_obj_set_flex_flow(ui_SystemMenuUpdateTab,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SystemMenuUpdateTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_SystemMenuUpdateTab, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenuUpdateTab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuUpdateFWversion = lv_label_create(ui_SystemMenuUpdateTab);
lv_obj_set_width( ui_SystemMenuUpdateFWversion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemMenuUpdateFWversion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuUpdateFWversion, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuUpdateFWversion,"Update Firmware");
lv_obj_set_style_text_font(ui_SystemMenuUpdateFWversion, &ui_font_MuseoSansRounded70016, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuUpdateMessage = lv_label_create(ui_SystemMenuUpdateTab);
lv_obj_set_width( ui_SystemMenuUpdateMessage, lv_pct(100));
lv_obj_set_height( ui_SystemMenuUpdateMessage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuUpdateMessage, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuUpdateMessage,"Insert an SD card or USB drive containing a firmware update file.");
lv_obj_set_style_text_color(ui_SystemMenuUpdateMessage, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SystemMenuUpdateMessage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SystemMenuUpdateMessage, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenuUpdateFWBut = lv_btn_create(ui_SystemMenuUpdateTab);
lv_obj_set_width( ui_SystemMenuUpdateFWBut, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_SystemMenuUpdateFWBut, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SystemMenuUpdateFWBut, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SystemMenuUpdateFWBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SystemMenuUpdateFWBut, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemMenuUpdateFWBut, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemMenuUpdateFWBut, lv_color_hex(0x777777), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenuUpdateFWBut, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SystemMenuUpdateFWBut, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_SystemMenuUpdateFWBut, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_SystemMenuUpdateFWBut, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_SystemMenuUpdateFWBut, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_SystemMenuUpdateFWBut, lv_color_hex(0xFD8B18), LV_PART_MAIN | LV_STATE_FOCUS_KEY );
lv_obj_set_style_outline_opa(ui_SystemMenuUpdateFWBut, 255, LV_PART_MAIN| LV_STATE_FOCUS_KEY);

ui_SystemMenuUpdateFWlabel = lv_label_create(ui_SystemMenuUpdateFWBut);
lv_obj_set_width( ui_SystemMenuUpdateFWlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemMenuUpdateFWlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemMenuUpdateFWlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemMenuUpdateFWlabel,"Update Firmware");
lv_obj_set_style_text_font(ui_SystemMenuUpdateFWlabel, &ui_font_MuseoSansRounded70014, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemMenUpdateProgressBar = lv_bar_create(ui_SystemMenuUpdateTab);
lv_bar_set_value(ui_SystemMenUpdateProgressBar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_SystemMenUpdateProgressBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SystemMenUpdateProgressBar, 296);
lv_obj_set_height( ui_SystemMenUpdateProgressBar, 12);
lv_obj_set_align( ui_SystemMenUpdateProgressBar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SystemMenUpdateProgressBar, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_bg_color(ui_SystemMenUpdateProgressBar, lv_color_hex(0xFF8918), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemMenUpdateProgressBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_FWUpdateSpinner = lv_spinner_create(ui_SystemMenuUpdateTab,1000,90);
lv_obj_set_width( ui_FWUpdateSpinner, 50);
lv_obj_set_height( ui_FWUpdateSpinner, 50);
lv_obj_set_x( ui_FWUpdateSpinner, 0 );
lv_obj_set_y( ui_FWUpdateSpinner, 40 );
lv_obj_set_align( ui_FWUpdateSpinner, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_FWUpdateSpinner, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING );   /// Flags
lv_obj_clear_flag( ui_FWUpdateSpinner, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_arc_color(ui_FWUpdateSpinner, lv_color_hex(0xFF8918), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_FWUpdateSpinner, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_FWUpdateSpinner, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_FWUpdateSpinner, lv_color_hex(0xFF8918), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_FWUpdateSpinner, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_FWUpdateSpinner, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_FWUpdateSpinner, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
