name: Run VCV unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '83-*'
    paths:
      - 'vcv/**'
      - 'shared/**'
      - '!**.md' # Skip docs
      - '!shared/svgextract' # Skip generator script (still run CI if generated files change)
      - '!shared/gen_minblep' # Skip generator script (still run CI if generated files change)
      - '!shared/tableGen' # Skip generator script (still run CI if generated files change)

env:
  rack-sdk-version: 2.3.0

jobs:
  build:
    
    strategy:
      fail-fast: false
      matrix:
        os: 
          # - { os: windows, shell: msys2, rack-os-name: win-x64 }    # runs out of memory - "cc1plus.exe: out of memory allocating 65536 bytes"
          - { os: ubuntu,  shell: bash, rack-os-name: lin-x64  }      
    runs-on: '${{ matrix.os.os }}-latest'
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: gcc
      CXX: g++

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install windows dependencies (MSYS2)
        if: matrix.os.os =='windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            git wget make tar unzip zip mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb mingw-w64-x86_64-cmake autoconf automake libtool mingw-w64-x86_64-jq python zstd mingw-w64-x86_64-pkgconf

      - name: Get Rack-SDK
        run: |
          pushd $HOME
          curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-${{ matrix.os.rack-os-name }}.zip
          unzip Rack-SDK.zip

      - name: Build and run tests
        run: |
          export RACK_DIR=$HOME/Rack-SDK
          cd vcv
          make -f tests/Makefile
