// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: META5

#include "../ui.h"

void ui_Mapping_Menu_screen_init(void)
{
ui_Mapping_Menu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Mapping_Menu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MappingFlexZone = lv_obj_create(ui_Mapping_Menu);
lv_obj_set_width( ui_MappingFlexZone, 333);
lv_obj_set_height( ui_MappingFlexZone, 240);
lv_obj_set_align( ui_MappingFlexZone, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_MappingFlexZone,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_MappingFlexZone, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_MappingFlexZone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MappingFlexZone, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MappingFlexZone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MappingFlexZone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MappingFlexZone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MappingFlexZone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MappingFlexZone, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MappingFlexZone, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MappingFlexZone, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MappingFlexZone, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MappingFlexZone, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MappingFlexZone, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MappingFlexZone, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MappingFlexZone, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MappingFlexZone, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_ModuleImage = lv_obj_create(ui_MappingFlexZone);
lv_obj_set_width( ui_ModuleImage, 143);
lv_obj_set_height( ui_ModuleImage, 240);
lv_obj_set_x( ui_ModuleImage, -15 );
lv_obj_set_y( ui_ModuleImage, -1 );
lv_obj_set_align( ui_ModuleImage, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_ModuleImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ModuleImage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ModuleImage, &ui_img_complexeg_mockup_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_ModuleImage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ModuleImage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ModuleImage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_ModuleImage, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ModuleImage, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ModuleImage, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_MappingParameters = lv_obj_create(ui_MappingFlexZone);
lv_obj_set_height( ui_MappingParameters, 240);
lv_obj_set_flex_grow( ui_MappingParameters, 1);
lv_obj_set_align( ui_MappingParameters, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_MappingParameters,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_MappingParameters, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_MappingParameters, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_MappingParameters, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MappingParameters, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MappingParameters, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MappingParameters, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MappingParameters, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MappingParameters, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MappingParameters, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_MappingParameters, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_MappingParameters, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_MappingParameters, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_MappingParameters, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MappingParameters, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MappingParameters, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MappingParameters, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MappingParameters, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MappingParameters, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Module_Name = lv_label_create(ui_MappingParameters);
lv_obj_set_height( ui_Module_Name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_Module_Name, 1);
lv_obj_set_x( ui_Module_Name, -67 );
lv_obj_set_y( ui_Module_Name, -113 );
lv_obj_set_align( ui_Module_Name, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Module_Name,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Module_Name,"Module Name xX - 0123");
lv_obj_set_scrollbar_mode(ui_Module_Name, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_Module_Name, LV_DIR_RIGHT);
lv_obj_set_style_text_color(ui_Module_Name, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Module_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Module_Name, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Module_Name, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Module_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Module_Name, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Module_Name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Module_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Module_Name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Module_Name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Module_Name, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Module_Name, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Module_Name, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Module_Name, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Element_Name = lv_label_create(ui_MappingParameters);
lv_obj_set_height( ui_Element_Name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_Element_Name, 1);
lv_obj_set_x( ui_Element_Name, -67 );
lv_obj_set_y( ui_Element_Name, -113 );
lv_obj_set_align( ui_Element_Name, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Element_Name,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Element_Name,"Element Name xX - 0123");
lv_obj_add_flag( ui_Element_Name, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_set_scrollbar_mode(ui_Element_Name, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_Element_Name, LV_DIR_LEFT);
lv_obj_set_style_text_color(ui_Element_Name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Element_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Element_Name, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Element_Name, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Element_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Element_Name, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Element_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Element_Name, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Element_Name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Element_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Element_Name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Element_Name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Element_Name, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Element_Name, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Element_Name, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Element_Name, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MappedWindow = lv_textarea_create(ui_MappingParameters);
lv_obj_set_height( ui_MappedWindow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_MappedWindow, 1);
lv_obj_set_align( ui_MappedWindow, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_MappedWindow,"MAPPED TO\n");
lv_obj_add_flag( ui_MappedWindow, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_set_scrollbar_mode(ui_MappedWindow, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_MappedWindow, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MappedWindow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_MappedWindow, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_MappedWindow, 9, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MappedWindow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MappedWindow, &ui_font_Arial_16_bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_MappedWindow, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MappedWindow, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MappedWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MappedWindow, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MappedWindow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MappedWindow, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_MappedWindow, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_MappedWindow, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_MappedWindow, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_MappedWindow, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_MappedWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MappedWindow, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MappedWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MappedWindow, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MappedWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MappedWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MappedWindow, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Mappedto = lv_img_create(ui_MappedWindow);
lv_img_set_src(ui_Mappedto, &ui_img_button_circles_asset_34_png);
lv_obj_set_width( ui_Mappedto, 22);
lv_obj_set_height( ui_Mappedto, 22);
lv_obj_set_align( ui_Mappedto, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Mappedto, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Mappedto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_EditMapButton = lv_imgbtn_create(ui_MappingParameters);
lv_imgbtn_set_src(ui_EditMapButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1x_edit_map2_png, NULL);
lv_imgbtn_set_src(ui_EditMapButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1x_edit_map2_png, NULL);
lv_obj_set_width( ui_EditMapButton, 80);
lv_obj_set_height( ui_EditMapButton, 30);
lv_obj_set_align( ui_EditMapButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_EditMapButton, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK );   /// Flags
lv_obj_set_style_radius(ui_EditMapButton, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_EditMapButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_EditMapButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_EditMapButton, LV_GRAD_DIR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_EditMapButton, lv_color_hex(0xEC1C24), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_EditMapButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_EditMapButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_EditMapButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_EditMapButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_EditMapButton, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_EditMapButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_EditMapButton, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_EditMapButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_EditMapButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_EditMapButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_radius(ui_EditMapButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_color(ui_EditMapButton, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_outline_opa(ui_EditMapButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_width(ui_EditMapButton, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_outline_pad(ui_EditMapButton, 3, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_color(ui_EditMapButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_shadow_opa(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_width(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_spread(ui_EditMapButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_ElementRoller = lv_roller_create(ui_MappingFlexZone);
lv_roller_set_options( ui_ElementRoller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_ElementRoller, 234);
lv_obj_set_flex_grow( ui_ElementRoller, 1);
lv_obj_set_x( ui_ElementRoller, 169 );
lv_obj_set_y( ui_ElementRoller, -2 );
lv_obj_set_align( ui_ElementRoller, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_ElementRoller, ui_event_ElementRoller, LV_EVENT_ALL, NULL);

}
