// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: META6

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Dropdown_Animation( lv_obj_t *TargetObject, int delay);
void Dropup_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_PatchSelectorPage
void ui_PatchSelectorPage_screen_init(void);
lv_obj_t *ui_PatchSelectorPage;
lv_obj_t *ui_PatchSelectorTitle;
lv_obj_t *ui_DrivesPanel;
lv_obj_t *ui_USBbut;
lv_obj_t *ui_USBlabel;
lv_obj_t *ui_SDbut;
lv_obj_t *ui_SDlabel;
lv_obj_t *ui_Flashbut;
lv_obj_t *ui_Flashlabel;
lv_obj_t *ui_PatchListRoller;
lv_obj_t *ui_waitspinner;

// SCREEN: ui_PatchViewPage
void ui_PatchViewPage_screen_init(void);
lv_obj_t *ui_PatchViewPage;
lv_obj_t *ui_ButtonsContainer;
lv_obj_t *ui_PlayButton;
lv_obj_t *ui_KnobButton;
lv_obj_t *ui_AddButton;
lv_obj_t *ui_InfoButton;
lv_obj_t *ui_SettingsButton;
lv_obj_t *ui_PatchName;
lv_obj_t *ui_ModulesPanel;
lv_obj_t *ui_SettingsMenu;
lv_obj_t *ui_SettingsClosePanel;
lv_obj_t *ui_SettingsHeaderLabel;
lv_obj_t *ui_SettingsCloseButton;
lv_obj_t *ui_SettingsMapsTitle;
lv_obj_t *ui_ShowAllMapsPanel;
lv_obj_t *ui_ShowAllMapsLabel;
lv_obj_t *ui_ShowAllMapsCheck;
lv_obj_t *ui_ShowCurrentPanel;
lv_obj_t *ui_ShowCurrentLabel;
lv_obj_t *ui_ShowSelectedMapsCheck;
lv_obj_t *ui_ShowPlayingMapsPanel;
lv_obj_t *ui_ShowPlayingMapsLabel;
lv_obj_t *ui_ShowPlayingMapsCheck;
lv_obj_t *ui_FlashMapPanel;
lv_obj_t *ui_FlashMapLabel;
lv_obj_t *ui_FlashMapCheck;
lv_obj_t *ui_Label1;
lv_obj_t *ui_MapTranspSlider;
lv_obj_t *ui_CablesTitle;
lv_obj_t *ui_ShowAllCablesPanel;
lv_obj_t *ui_ShowAllCablesLabel;
lv_obj_t *ui_ShowAllCablesCheck;

// SCREEN: ui_PatchViewPage2
void ui_PatchViewPage2_screen_init(void);
lv_obj_t *ui_PatchViewPage2;
lv_obj_t *ui_PatchName2;
lv_obj_t *ui_ButtonsContainer2;
lv_obj_t *ui_PlayButton2;
lv_obj_t *ui_KnobButton2;
lv_obj_t *ui_AddButton2;
lv_obj_t *ui_InfoButton2;
lv_obj_t *ui_SettingsButton2;
lv_obj_t *ui_ModulesPanel2;

// SCREEN: ui_MappingMenu
void ui_MappingMenu_screen_init(void);
lv_obj_t *ui_MappingMenu;
lv_obj_t *ui_MappingFlexZone;
lv_obj_t *ui_ModuleImage;
lv_obj_t *ui_MappingParameters;
lv_obj_t *ui_Module_Name;
lv_obj_t *ui_Element_Name;
lv_obj_t *ui_MappedWindow;
lv_obj_t *ui_Mappedto;
lv_obj_t *ui_EditMapButton;
lv_obj_t *ui_NotMapped;
lv_obj_t *ui_ModuleName1;
lv_obj_t *ui_ElementName1;
lv_obj_t *ui_MappedWindow1;
void ui_event_AddMapButton( lv_event_t * e);
lv_obj_t *ui_AddMapButton;
lv_obj_t *ui_AddMapButton1;
void ui_event_ElementRoller( lv_event_t * e);
lv_obj_t *ui_ElementRoller;
lv_obj_t *ui_AddMapPopUp;
lv_obj_t *ui_AddPrompt;
lv_obj_t *ui_MapDetected;
lv_obj_t *ui_canceladd;
void ui_event_okadd( lv_event_t * e);
lv_obj_t *ui_okadd;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_addmap[1] = {&ui_img_1x_addmap1_png};
const lv_img_dsc_t *ui_imgset_control[1] = {&ui_img_1x_control1_png};
const lv_img_dsc_t *ui_imgset_editmap[1] = {&ui_img_1x_editmap2_png};
const lv_img_dsc_t *ui_imgset_dark_settings_focused_red[1] = {&ui_img_dark_icons_dark_settings_focused_red2_png};
const lv_img_dsc_t *ui_imgset_dark_settings_focused[1] = {&ui_img_dark_icons_dark_settings_focused3_png};
const lv_img_dsc_t *ui_imgset_info_light[4] = {&ui_img_symbols_raw_light_info_light1_png, &ui_img_symbols_raw_light_info_light2_png, &ui_img_symbols_raw_light_info_light3_png, &ui_img_symbols_raw_light_info_light4_png};
const lv_img_dsc_t *ui_imgset_knob_light[3] = {&ui_img_symbols_raw_light_knob_light1_png, &ui_img_symbols_raw_light_knob_light2_png, &ui_img_symbols_raw_light_knob_light3_png};
const lv_img_dsc_t *ui_imgset_play_light[2] = {&ui_img_symbols_raw_light_play_light1_png, &ui_img_symbols_raw_light_play_light2_png};
const lv_img_dsc_t *ui_imgset_plus_light[2] = {&ui_img_symbols_raw_light_plus_light1_png, &ui_img_symbols_raw_light_plus_light2_png};
const lv_img_dsc_t *ui_imgset_settings_light[2] = {&ui_img_symbols_raw_light_settings_light2_png, &ui_img_symbols_raw_light_settings_light27_png};
const lv_img_dsc_t *ui_imgset_info_dark[4] = {&ui_img_symbols_raw_info_dark1_png, &ui_img_symbols_raw_info_dark2_png, &ui_img_symbols_raw_info_dark3_png, &ui_img_symbols_raw_info_dark4_png};
const lv_img_dsc_t *ui_imgset_knob_dark[3] = {&ui_img_symbols_raw_knob_dark1_png, &ui_img_symbols_raw_knob_dark2_png, &ui_img_symbols_raw_knob_dark3_png};
const lv_img_dsc_t *ui_imgset_play_dark[2] = {&ui_img_symbols_raw_play_dark1_png, &ui_img_symbols_raw_play_dark2_png};
const lv_img_dsc_t *ui_imgset_plus_dark[2] = {&ui_img_symbols_raw_plus_dark1_png, &ui_img_symbols_raw_plus_dark2_png};
const lv_img_dsc_t *ui_imgset_settings_dark[2] = {&ui_img_symbols_raw_settings_dark2_png, &ui_img_symbols_raw_settings_dark27_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Dropdown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 250);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_0, 0, 240 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void Dropup_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 200);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_0, 240, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_AddMapButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AddMapPopUp, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_ElementRoller( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_MappingParameters, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_ElementRoller, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_okadd( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_AddMapPopUp, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_PatchSelectorPage_screen_init();
ui_PatchViewPage_screen_init();
ui_PatchViewPage2_screen_init();
ui_MappingMenu_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_PatchSelectorPage);
}
