// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: META6

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Dropdown_Animation( lv_obj_t *TargetObject, int delay);
void Dropup_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_PatchSelectorPage
void ui_PatchSelectorPage_screen_init(void);
lv_obj_t *ui_PatchSelectorPage;
lv_obj_t *ui_PatchSelectorTitlePanel;
lv_obj_t *ui_PatchSelectorTitle;
lv_obj_t *ui_NowPlayingName;
lv_obj_t *ui_LoadMeter;
lv_obj_t *ui_DrivesPanel;
lv_obj_t *ui_USBbut;
lv_obj_t *ui_USBlabel;
lv_obj_t *ui_USBlabel1;
lv_obj_t *ui_SDbut;
lv_obj_t *ui_SDlabel;
lv_obj_t *ui_SDlabel1;
lv_obj_t *ui_Flashbut;
lv_obj_t *ui_Flashlabel;
lv_obj_t *ui_Flashlabel1;
lv_obj_t *ui_PatchListRoller;
lv_obj_t *ui_waitspinner;


// SCREEN: ui_PatchViewPage
void ui_PatchViewPage_screen_init(void);
lv_obj_t *ui_PatchViewPage;
lv_obj_t *ui_ButtonsContainer;
lv_obj_t *ui_PlayButton;
lv_obj_t *ui_KnobButton;
lv_obj_t *ui_AddButton;
lv_obj_t *ui_InfoButton;
lv_obj_t *ui_SettingsButton;
lv_obj_t *ui_PatchName;
lv_obj_t *ui_ModulesPanel;
lv_obj_t *ui_SettingsMenu;
lv_obj_t *ui_SettingsClosePanel;
lv_obj_t *ui_SettingsHeaderLabel;
lv_obj_t *ui_SettingsCloseButton;
lv_obj_t *ui_SettingsMapsTitle;
lv_obj_t *ui_ShowAllMapsPanel;
lv_obj_t *ui_ShowAllMapsLabel;
lv_obj_t *ui_ShowAllMapsCheck;
lv_obj_t *ui_ShowCurrentPanel;
lv_obj_t *ui_ShowCurrentLabel;
lv_obj_t *ui_ShowSelectedMapsCheck;
lv_obj_t *ui_ShowPlayingMapsPanel;
lv_obj_t *ui_ShowPlayingMapsLabel;
lv_obj_t *ui_ShowPlayingMapsCheck;
lv_obj_t *ui_FlashMapPanel;
lv_obj_t *ui_FlashMapLabel;
lv_obj_t *ui_FlashMapCheck;
lv_obj_t *ui_MapsTransparencyTitle;
lv_obj_t *ui_MapTranspSlider;
lv_obj_t *ui_CablesTitle;
lv_obj_t *ui_ShowAllCablesPanel;
lv_obj_t *ui_ShowAllCablesLabel;
lv_obj_t *ui_ShowAllCablesCheck;
lv_obj_t *ui_CablesTransparencyTitle;
lv_obj_t *ui_CablesTranspSlider;
lv_obj_t *ui_KnobsetMenu;
lv_obj_t *ui_KnobSetClosePanel;
lv_obj_t *ui_KnobsetHeaderLabel;
lv_obj_t *ui_KnobsetCloseButton;
lv_obj_t *ui_KnobsetHeaderLine;


// SCREEN: ui_MappingMenu
void ui_MappingMenu_screen_init(void);
lv_obj_t *ui_MappingMenu;
lv_obj_t *ui_MappingFlexZone;
lv_obj_t *ui_ModuleImage;
lv_obj_t *ui_ElementRoller;
lv_obj_t *ui_MappingParameters;
lv_obj_t *ui_Module_Name;
lv_obj_t *ui_Element_Name;
lv_obj_t *ui_ControlButton;
lv_obj_t *ui_ControlButtonLabel;
lv_obj_t *ui_MappedPanel;
lv_obj_t *ui_MappedListTitle;
lv_obj_t *ui_MappedListPane;
lv_obj_t *ui_MappedItemHeader;
lv_obj_t *ui_MappedItemHeaderMapText;
lv_obj_t *ui_MappedItemHeaderKnobSetText;
lv_obj_t *ui_MappedItemHeaderAddText;
lv_obj_t *ui_MapList;
lv_obj_t *ui_MappedKnobSetItem1;
lv_obj_t *ui_UnmappedSetItem1;
lv_obj_t *ui_UnmappedSetItem2;
lv_obj_t *ui_MappedKnobSetItem2;
lv_obj_t *ui_ControlAlert;
lv_obj_t *ui_ControlArc;
lv_obj_t *ui_ControlAlertLabel;
lv_obj_t *ui_AddMapPopUp;
lv_obj_t *ui_AddModuleName;
lv_obj_t *ui_MapDetected;
lv_obj_t *ui_CancelAdd;
lv_obj_t *ui_CancelAddLabel;
lv_obj_t *ui_OkAdd;
lv_obj_t *ui_OkAddLabel;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_add[1] = {&ui_img_1x_add1_png};
const lv_img_dsc_t *ui_imgset_info[1] = {&ui_img_1x_info1_png};
const lv_img_dsc_t *ui_imgset_knob[1] = {&ui_img_1x_knob1_png};
const lv_img_dsc_t *ui_imgset_play[1] = {&ui_img_1x_play1_png};
const lv_img_dsc_t *ui_imgset_settings[1] = {&ui_img_1x_settings1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Dropdown_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 250);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 230, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}
void Dropup_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 250);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 220 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_PatchSelectorPage_screen_init();
ui_PatchViewPage_screen_init();
ui_MappingMenu_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_PatchSelectorPage);
}
