// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: META5

#ifndef _META5_UI_H
#define _META5_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_PatchViewPage
void ui_PatchViewPage_screen_init(void);
extern lv_obj_t *ui_PatchViewPage;
extern lv_obj_t *ui_PatchName;
extern lv_obj_t *ui_ButtonsBG;
extern lv_obj_t *ui_ButtonsContainer;
extern lv_obj_t *ui_PlayButton;
void ui_event_KnobButton( lv_event_t * e);
extern lv_obj_t *ui_KnobButton;
extern lv_obj_t *ui_AddButton;
extern lv_obj_t *ui_InfoButton;
extern lv_obj_t *ui_SettingsButton;
// SCREEN: ui_Mapping_Menu
void ui_Mapping_Menu_screen_init(void);
extern lv_obj_t *ui_Mapping_Menu;
extern lv_obj_t *ui_MappingFlexZone;
extern lv_obj_t *ui_ModuleImage;
extern lv_obj_t *ui_MappingParameters;
extern lv_obj_t *ui_Module_Name;
extern lv_obj_t *ui_Element_Name;
extern lv_obj_t *ui_MappedWindow;
extern lv_obj_t *ui_Mappedto;
extern lv_obj_t *ui_EditMapButton;
void ui_event_ElementRoller( lv_event_t * e);
extern lv_obj_t *ui_ElementRoller;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_dark_icons_dark_play_png);   // assets/Dark Icons/Dark Play.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_play_press_png);   // assets/Dark Icons/Dark Play Press.png
LV_IMG_DECLARE( ui_img_dark_icons_32px_circle_png);   // assets/Dark Icons/32px circle.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_knob_png);   // assets/Dark Icons/Dark Knob.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_knob_press_png);   // assets/Dark Icons/Dark Knob Press.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_add_png);   // assets/Dark Icons/Dark Add.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_add_press_png);   // assets/Dark Icons/Dark Add Press.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_info_png);   // assets/Dark Icons/Dark Info.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_info_press_png);   // assets/Dark Icons/Dark Info Press.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_settings_png);   // assets/Dark Icons/Dark Settings.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_settings_pressed_png);   // assets/Dark Icons/Dark Settings Pressed.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_settings_focused3_png);   // assets/Dark Icons/Dark Settings Focused3.png
LV_IMG_DECLARE( ui_img_complexeg_mockup_png);   // assets/ComplexEG_mockup.png
LV_IMG_DECLARE( ui_img_button_circles_asset_34_png);   // assets/Button Circles/Asset 34.png
LV_IMG_DECLARE( ui_img_1x_edit_map2_png);   // assets/1x/edit_map2.png
LV_IMG_DECLARE( ui_img_1x_edit_map1_png);   // assets/1x/edit_map1.png
LV_IMG_DECLARE( ui_img_button_circles_asset_35_png);   // assets/Button Circles/Asset 35.png
LV_IMG_DECLARE( ui_img_button_circles_asset_36_png);   // assets/Button Circles/Asset 36.png
LV_IMG_DECLARE( ui_img_button_circles_asset_46_png);   // assets/Button Circles/Asset 46.png
LV_IMG_DECLARE( ui_img_button_circles_asset_47_png);   // assets/Button Circles/Asset 47.png
LV_IMG_DECLARE( ui_img_button_circles_asset_48_png);   // assets/Button Circles/Asset 48.png
LV_IMG_DECLARE( ui_img_dark_icons_dark_settings_focused_red2_png);   // assets/Dark Icons/Dark Settings Focused Red2.png

LV_FONT_DECLARE( ui_font_Arial11bpp4);
LV_FONT_DECLARE( ui_font_Arial12bpp4);
LV_FONT_DECLARE( ui_font_Arial_16_bpp4);
LV_FONT_DECLARE( ui_font_GIL12);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
